/**
 * English translations for /templates/[type] marketing copy.
 *
 * Phase 4 incremental rollout: only entries listed here unlock the /en/templates/[type]
 * route. zh-only categories (~17 of 20) keep returning notFound() on /en until translated.
 *
 * Coverage so far: stool, pencil-holder, side-table — the 3 templates that are free on
 * any plan, so /en visitors can preview without paywall friction.
 *
 * Add a new entry → /en/templates/{category} auto-unlocks via getTemplateMarketing.
 */
import type { FurnitureCategory } from "../types";
import type { TemplateMarketing } from "./marketing";

const M_EN = {
  stool: {
    category: "stool",
    seoTitle: "Square stool plans | Auto-generated 3-views, joinery, cut list — Wooden Ren Blueprint",
    seoDescription: "Build a four-leg stool from sizes to shop drawings in three seconds. Auto-laid mortise positions, three-view drawings, cut list. Free template. From Wooden Ren Carpenter Academy.",
    tagline: "Start your first mortise-and-tenon on a stool that's yours",
    subTagline: "Free template · build as many as you want · 30 min to grok joinery logic",
    whatItDoes: "A four-leg square stool is the classic woodworking starter — four legs, four aprons, one seat. Get those six things right and you've already nailed 80% of furniture joinery fundamentals.\n\nThis template takes length × width × height and lays out every mortise position, tenon depth (through for ≤25 mm legs, blind at 2/3 depth above), and how the X-axis and Z-axis aprons must stagger so they don't collide in the leg. You stop worrying \"are the legs too thin?\" \"will a thick apron split the leg?\" — the algorithm checks for you, and the output is ready for the shop.\n\nAfter one stool, every other piece of furniture starts to look like a scaled-up version of the same joinery: dining chairs, side tables, desks — same logic, bigger numbers.",
    keywords: ["square stool plans", "stool dimensions", "stool mortise and tenon", "DIY wooden stool", "woodworking starter project"],
    fitFor: {
      good: ["First-timers learning mortise-and-tenon", "Want to design furniture without learning CAD", "Looking for a small gift project to practice on"],
      notFor: ["Want to build large furniture (try dining-chair / dining-table)", "Pure design theorists who don't want to actually build"],
    },
    parameters: [
      { label: "L × W × H", desc: "Free plan capped at 35×35×45 cm; paid plans unlock any size" },
      { label: "Leg profile", desc: "Square or round — algorithm auto-fits mortise shape" },
      { label: "Apron height", desc: "Auto-scaled to seat width; flags when ratio is unsafe" },
      { label: "Splay angle", desc: "0° straight / 5–12° splayed, includes compound-angle math" },
    ],
    scenarios: [
      { tag: "Classroom", body: "Pull up the designer on every student's phone, each enters their own size — 30 minutes from abstract idea to drawings they can build." },
      { tag: "Weekend build", body: "Enter sizes Friday night, buy stock Saturday, build Sunday — one stool in three days." },
      { tag: "Gift build", body: "Measure the actual corner in a friend's home, build a one-off size that fits — far more meaningful than another IKEA piece." },
      { tag: "Father's Day", body: "Start two weeks before — a stool engraved with his initials beats anything off a department-store shelf." },
    ],
    faqs: [
      { q: "Why is the free plan capped at 35×35×45 cm?", a: "That's the natural \"stool\" envelope — anything larger becomes a low table and effectively a paid template. Upgrade to Personal to unlock any size." },
      { q: "Are thinner legs more elegant?", a: "Visually, yes. Structurally — too thin and once you cut a mortise there's barely any meat left to carry the load. The designer warns you when ratios go bad, but the final call is yours." },
      { q: "Can I build a round stool here?", a: "Round stools use a different leg algorithm (typically 3–4 splayed legs). Use the round-stool template instead." },
      { q: "How deep should the mortise be?", a: "Through tenon: depth = leg width. Blind tenon: 2/3 of apron thickness (e.g. 18 mm apron → 12 mm mortise). Too shallow pulls out; too deep blows out the back. The algorithm computes this from your apron thickness." },
      { q: "What tools do I need?", a: "Minimum: a saw (hand or table), 3 chisels (6/9/12 mm), a mallet, and either a hand drill or a mortiser. Power tools speed things up but hand tools work fine." },
    ],
    presets: [
      { name: "Straight-leg classic", desc: "Square straight legs — standard starter for learning mortises, easiest structure to reason about." },
      { name: "8° splayed", desc: "Legs leaning out 8° — visually lighter, compound geometry handled by the algorithm." },
      { name: "Tapered leg", desc: "Tapered toward the foot — common Nordic proportion, cuts apparent weight in half." },
      { name: "Wide-seat foot stool", desc: "Seat widened to 40 cm with a lower stretcher — works as a footstool or step." },
      { name: "Through-tenon decorative", desc: "Apron tenons run all the way through the leg, exposed end-grain on the outside — Ming-style traditional craft look." },
    ],
    howToSteps: [
      { name: "Mill and prep stock", text: "Cut leg, apron and seat stock to the cut-list sizes plus 5 mm of trim allowance per part. Square the end grain on the table saw." },
      { name: "Chop the apron mortises", text: "On each of the four legs, chop the apron mortises with a 9 or 12 mm chisel. Blind tenon depth = 2/3 of apron thickness (18 mm apron → 12 mm mortise). The two apron pairs need to stagger by 5 mm so corner tenons don't collide." },
      { name: "Cut the apron tenons", text: "Cut tenons on both ends of each apron. Mark shoulders carefully, table-saw the shoulders clean, then pare with a chisel until the tenon slides snug into the mortise without rocking." },
      { name: "Dry-fit and adjust", text: "Assemble four legs and four aprons dry. Check 90° at every corner with a try-square; diagonals equal. Pare any shoulder that's racking the frame." },
      { name: "Glue-up", text: "Disassemble, glue mortises and tenons evenly, reassemble in one pass with diagonal clamping. Re-check square after 30 minutes." },
      { name: "Sand and finish", text: "After glue cures: 120 → 180 → 240 grit with the grain. Two to three coats of Danish oil or water-based polyurethane, light sanding between coats." },
    ],
    related: ["round-stool", "bench", "side-table"],
  },
  "pencil-holder": {
    category: "pencil-holder",
    seoTitle: "Pencil holder plans | Square / hex / octagonal auto-modeling — Wooden Ren Blueprint",
    seoDescription: "Build a pencil holder in 10 minutes — the cheapest way to practice mitered and finger joints. Square, hex, octagonal, divided, brush holder — 6 presets, free to try.",
    tagline: "10 minutes to a pencil holder — the cheapest joinery practice there is",
    subTagline: "Free template · 6 presets (square / hex / octagonal / divided / brush holder / partitioned)",
    whatItDoes: "A pencil holder is the highest-ROI way to practice joinery — scrap stock under a dollar each, and you can drill on 30° / 45° / 60° miters, learn dado-housed dividers, edge-jointed panels and chamfered edges all on one piece.\n\nThis template supports 6 presets: simple square, divided desk grid, brush holder, tool tote, hexagonal tea caddy, octagonal cross-section. Each one auto-computes the miter angle, divider lengths, and the matching dado depth. Octagonal corners are 135° interior (which means a 22.5° saw-blade angle) — easy to get wrong by hand; the cut list just tells you \"set the table-saw blade to 22.5° and cut 8 pieces\".\n\nMake one for yourself, gift one to a friend, sell them at a craft market — pencil holders give the best learning per dollar of any woodworking project.",
    keywords: ["pencil holder plans", "wooden pencil holder", "hex box angle", "octagonal miter", "DIY desk organizer"],
    fitFor: {
      good: ["Practicing mitered joinery", "Using up scrap stock", "Selling at craft markets"],
      notFor: ["Looking to build large storage cabinets"],
    },
    parameters: [
      { label: "Shape", desc: "Square / hexagonal / octagonal / oval" },
      { label: "Size", desc: "Free plan capped at 20 × 20 × 25 cm" },
      { label: "Dividers", desc: "0–6 compartments — algorithm lays them out and computes dado depth" },
      { label: "Joinery", desc: "Mitered / finger / dovetailed — algorithm picks the most stock-efficient" },
    ],
    scenarios: [
      { tag: "Scrap-stock cleanup", body: "Got a pile of offcuts gathering dust? Ten pencil holders eats through it." },
      { tag: "Kids' project", body: "Design a pencil holder with your kid. 30 minutes from sketch to finished piece — they'll use it daily, more than any parenting blog can deliver." },
      { tag: "Craft market", body: "Made from shop scrap (cost under $1), sold at $8–15 each — viable weekend market stall margin." },
      { tag: "School project", body: "Hexagonal tea caddy is just hard enough to impress, just cheap enough to actually finish — perfect end-of-semester woodworking project." },
    ],
    presets: [
      { name: "Simple square", desc: "The simplest starter — four mitered boards." },
      { name: "Desk grid", desc: "4-compartment divider, salvation for desk OCD." },
      { name: "Brush holder", desc: "Tall body with shelf inserts — solid partner gift." },
      { name: "Tool tote", desc: "Holds planes and chisels point-up — bench-edge essential for any shop." },
      { name: "Hex tea caddy", desc: "Tea-people favorite — make it in cypress or pine and the aroma sticks around." },
      { name: "Octagonal cross", desc: "High-difficulty cross-section — finished piece photographs beautifully." },
    ],
    faqs: [
      { q: "What blade angle for a hex box?", a: "30° (each interior corner is 120°, so 180 − 120 = 60, and blade tilt is 60 / 2 = 30°). Octagonal is 22.5°. The cut list spells it out for each preset." },
      { q: "What wood works best?", a: "Use scrap. Cypress for aroma, oak for grain, pine for cheap — pencil holders aren't picky." },
      { q: "Can I build a bigger pencil holder?", a: "Free plan caps at 20 × 20 × 25 cm (anything bigger really becomes a vase or a storage tote). Upgrade to Personal for any size." },
      { q: "How do I glue mitered corners without slipping?", a: "Lay all 6 or 8 sides flat-edge-to-flat-edge on a strip of masking tape, glue, then fold up like a hinge — every corner closes simultaneously." },
      { q: "How deep should the divider dado be?", a: "Dado depth = 1/3 of divider thickness (9 mm divider → 3 mm dado). Too shallow rattles, too deep blows out the outside. The algorithm computes from your board thickness." },
    ],
    howToSteps: [
      { name: "Mill stock", text: "Pull scrap stock from the bin, leave 3 mm trim allowance, rip and crosscut to length, square the end grain." },
      { name: "Cut miters", text: "Set the table-saw blade to 45° for square, 30° for hex, 22.5° for octagonal. Miter both ends of every side. Dry-fit the corner — no gap = pass." },
      { name: "Cut divider dados", text: "If using dividers, dado the inside walls to 1/3 board thickness (9 mm board → 3 mm dado) with a router or hand saw. Dry-fit the divider — no wobble." },
      { name: "Glue with tape clamp", text: "Dry-fit all corners first. Lay flat-edge-to-flat-edge on a strip of masking tape, glue, fold up to close. Let cure 30 minutes before peeling tape." },
      { name: "Sand and finish", text: "Sand outside and rim at 180 → 240 grit. Apply one or two coats of beeswax or boiled linseed oil for a tactile, natural finish." },
    ],
    related: ["dovetail-box", "tray", "photo-frame"],
  },
  "side-table": {
    category: "side-table",
    seoTitle: "Side table plans | Sofa-side / nightstand auto 3-views — Wooden Ren Blueprint",
    seoDescription: "Build the side table that actually fits next to your sofa or bed — auto joinery, 3-view drawings, cut list. Drawer, shelf or plain top — 3 seconds to shop-ready plans.",
    tagline: "The right-sized little table next to the sofa or the bed",
    subTagline: "Drawer / shelf / plain-top variants",
    whatItDoes: "Side tables are the piece of furniture you can never buy in the right size — store-bought is either too tall, too wide, or visually mismatched with your sofa. Building one yourself is the only way to nail the exact armrest height of your couch, the exact gap beside your bed.\n\nThis template ships three variants: plain-top (fastest build), drawer (for remote / glasses storage) and lower-shelf (stacks books / magazines). The drawer slide position is auto-computed from drawer width — you just walk into the hardware store and ask for \"13-inch full-extension slides, one pair\". Legs come in straight, 5° splayed, or 10° splayed — splayed gives a lighter look but needs compound angles, which the algorithm handles and outputs as ready-to-cut true-length numbers.\n\nA hardwood (oak / walnut) side table runs $25–50 in materials — about twice the lumber quality of an IKEA LACK at the same overall cost, dimensioned exactly for your room. Once you've built one, you've unlocked all \"table-class joinery\" — coffee tables, dining tables, desks all scale from the same logic. Best of all: you remember which board came from which tree, every time you set a coffee mug down.",
    keywords: ["side table plans", "sofa side table", "nightstand plans", "small wood table", "side table dimensions"],
    fitFor: {
      good: ["Want to fit an exact spot in your living room", "Practicing \"table-class\" joinery as an intermediate builder", "Upgrading living-room atmosphere with DIY"],
      notFor: ["No saw and no workshop access", "Hoping to finish in three days as a beginner (splayed legs need compound-angle setup time)", "Strictly $10-or-under budget (you can't even buy the lumber for that)"],
    },
    parameters: [
      { label: "Size", desc: "Suggested 40–60 cm wide × 40–50 cm tall (handy mug-height from the sofa)" },
      { label: "Drawer", desc: "0–1 drawer; auto-computes slide location and hardware spec" },
      { label: "Lower shelf", desc: "Optional; great for stacking books" },
      { label: "Leg style", desc: "Straight / splayed / tapered — three options" },
    ],
    scenarios: [
      { tag: "New apartment", body: "Just moved in, and every off-the-shelf side table is 5 cm too tall or 3 cm too narrow. Measure once, build once, it fits." },
      { tag: "Wedding gift", body: "Build two identical side tables as a wedding present — far more presence than anything off a registry." },
      { tag: "Housewarming", body: "Hand-engrave the initials, gift it to friends moving into their first home — they'll use it daily and remember." },
      { tag: "Guest-house outfit", body: "4 matching nightstands needed for the guest house. Quoted at $110 each, build them yourself for $30 in materials with better quality." },
    ],
    faqs: [
      { q: "Are splayed legs always better looking?", a: "Visually, yes — they look lighter. But the compound-angle math makes them harder to cut clean. Build a straight-leg version first, then graduate to splayed on table #2." },
      { q: "How hard are drawers?", a: "Dovetailed drawers are an intermediate move, but the algorithm pre-lays the dovetails for you — you just saw to the lines. Less scary than it sounds." },
      { q: "How do I choose the height?", a: "Sit on the sofa you'll use it next to, hang your arm naturally — the height a coffee mug rests easily is the right height. Usually 45–55 cm. Every sofa is different; measure before you build." },
      { q: "What top thickness?", a: "18 mm is the minimum; spans under 40 cm hold up fine. 21 mm gives a heavier, more grounded look. Thicker reads more substantial." },
      { q: "Should the lower shelf be fixed or adjustable?", a: "Side tables usually have one shelf, and fixed is sturdier (screwed or joined). Adjustable shelves make sense in bookcases where you change book heights — overkill here." },
    ],
    presets: [
      { name: "Straight leg + plain top", desc: "Four straight legs and a top — the quickest build, low footprint next to the sofa." },
      { name: "Tapered leg + drawer", desc: "Tapered legs with a single drawer — remote / glasses storage, ideal bedside config." },
      { name: "Splayed leg + shelf", desc: "5° splayed legs with a lower magazine shelf — classic Scandinavian profile." },
      { name: "Cross-stretcher all-joinery", desc: "Adds a lower stretcher, fully mortise-and-tenon with no screws — showcase-grade craft." },
    ],
    howToSteps: [
      { name: "Mill and prep stock", text: "Cut leg / apron / top stock to size + 5 mm allowance. Table-saw to precise dimensions, square the ends with a sled or panel jig." },
      { name: "Cut joinery", text: "Mark mortise positions on the legs, chop to 2/3 apron thickness with a 12 mm chisel. Cut tenons on both apron ends, refine until they slide in snug without rocking." },
      { name: "Dry-fit", text: "Assemble all legs and aprons without glue. Try-square each corner; diagonals equal. Pare any shoulder that's racking the frame." },
      { name: "Glue-up", text: "Disassemble, glue mortise and tenon walls, reassemble in one continuous pass, diagonal clamps tight. Recheck diagonals after 30 minutes; release clamps after 24 hours." },
      { name: "Attach top, sand", text: "Mount the top from underneath with figure-8 fasteners, or seat it into a groove. Sand the whole piece 120 → 240 grit." },
      { name: "Finish", text: "Two coats of Danish oil, wipe surplus after 30 minutes per coat. Burnish lightly at 400 grit between the second and third coat for a silky feel." },
    ],
    related: ["tea-table", "low-table", "nightstand"],
  },
  bench: {
    category: "bench",
    seoTitle: "Bench plans | Entryway, dining bench, outdoor — Wooden Ren Blueprint",
    seoDescription: "Build a bench that actually fits your entry or dining table. Auto leg geometry, mid-span brace placement, load check. Three-second engineering drawings and cut list.",
    tagline: "Pulls double duty: entryway shoe bench or dining-table side seating",
    subTagline: "Intermediate template · straight / A-frame / trapezoid legs, mid-span brace optional",
    whatItDoes: "A bench is the most multipurpose piece of furniture in the house — entryway shoe bench, dining-table side seating (fits 3–4 people in one stretch), outdoor planter perch, library step. This template supports 90–200 cm lengths (anything > 150 cm gets an auto mid-span brace to prevent sag), three leg styles (straight / A-frame / trapezoid), and a bare or cushioned top. Materials run about $50–100 — cheaper than buying two IKEA chairs.\n\nStructurally a bench is the same \"legs + apron + top\" mortise-and-tenon as a stool. If you've built a stool, the only new challenge is span — tops over 120 cm need either edge-glued panels or a wood with stable fiber (oak / maple beat pine by a wide margin). Over 150 cm and you need a mid-stretcher or center leg.\n\nThe bench you build now will be sat on every day for 20 years. The shoe bench in the entryway is one of those things — pick a wood you like, finish it well, and it gets better with use.",
    keywords: ["bench plans", "entryway bench", "dining bench", "DIY wooden bench", "outdoor bench"],
    fitFor: {
      good: ["Building an entryway shoe bench", "Pairing benches with a dining table", "Outdoor garden seating"],
      notFor: ["Want a backrest (look at sofa or church-pew designs)", "Looking for a seat lower than 30 cm (use the low-table template)", "Outdoor use without exterior finish — wood will fail fast"],
    },
    parameters: [
      { label: "Length", desc: "90–200 cm; > 150 cm adds a mid-stretcher automatically" },
      { label: "Height", desc: "Shoe bench 40–45 cm, dining 42–45 cm, outdoor 45–50 cm" },
      { label: "Leg style", desc: "Straight (fastest) / A-frame (sturdiest) / trapezoid (most refined)" },
      { label: "Top", desc: "Edge-glued or single slab; bare or cushioned" },
    ],
    scenarios: [
      { tag: "Entryway", body: "90 × 30 × 45 cm shoe bench for the entryway — perch + slipper storage." },
      { tag: "Dining bench", body: "One bench + one row of chairs along the dining table — visual variety, fits 3–4 people on bench nights." },
      { tag: "Balcony perch", body: "Outdoor build — teak (or pine + exterior finish) — doubles as planter shelf." },
      { tag: "Housewarming gift", body: "Engraved with the address and year, set in the entryway, used for decades — beats cash." },
    ],
    faqs: [
      { q: "Does the bench need a backrest?", a: "Depends on use. Shoe / dining bench — no (need to swing on and off). Reading-nook bench — yes." },
      { q: "Do I need the mid-span brace?", a: "Over 150 cm, yes — otherwise the seat will sag a few mm over time even if it doesn't break." },
      { q: "What wood for outdoor?", a: "Teak is the gold standard (5–10 years), cypress is next, pine works only with annual exterior finish refresh." },
      { q: "Do I need to edge-glue the top?", a: "If the top is wider than 25 cm, yes — single slabs that wide tend to cup. A 30 cm-wide seat can be glued up from 2 × 15 cm boards — much more stable." },
      { q: "How are legs attached to the top?", a: "Two common options: through-tenon (leg passes through apron to underside of top) or blind tenon (apron has a half-tenon into the top). Through is strongest; blind is cleaner-looking. Both supported." },
    ],
    presets: [
      { name: "Straight-leg shoe bench", desc: "90 cm, straight legs, no back — finishes in a weekend." },
      { name: "A-frame dining bench", desc: "120 cm with A-frame legs — sturdy, seats three at the table, more compact than chairs." },
      { name: "Splayed low-back", desc: "Splayed legs + 150 mm low backrest — lumbar support for entryway shoe-changes." },
      { name: "Windsor high-back", desc: "Turned spindles + curved crest, 350 mm tall back — reading bench for the study." },
      { name: "Outdoor straight-leg", desc: "Teak or finished pine, 180 cm — patio planter seat." },
    ],
    howToSteps: [
      { name: "Mill stock", text: "Cut leg, apron and top stock to the cut-list + 5 mm allowance. Edge-glue the top if it exceeds 25 cm wide. Square the ends on the table saw." },
      { name: "Mortise legs and aprons", text: "Chop blind apron mortises (12 mm depth) on each leg; add center-leg mortises if length > 150 cm. Cut tenons on apron ends and dry-fit until snug." },
      { name: "Backrest (optional)", text: "For low/high-back versions, mortise the rear legs for the back panel or spindles. For Windsor styles, turn spindles to length and shoulder both ends." },
      { name: "Dry-fit", text: "Assemble legs and aprons dry. Confirm all four legs sit flat, diagonals equal, and (if splayed) the foot footprint is even." },
      { name: "Glue, sand, finish", text: "Glue and clamp; screw the top from underneath. After cure, sand 120 → 240. Outdoor: two coats of exterior finish. Indoor: Danish oil × 2 or water-based PU." },
    ],
    related: ["stool", "dining-chair", "side-table"],
  },
  "dining-chair": {
    category: "dining-chair",
    seoTitle: "Dining chair plans | Back curve, splayed legs, ergonomics — Wooden Ren Blueprint",
    seoDescription: "Build a dining chair you'll actually sit in for two hours. Algorithm auto-handles back-rake, compound-angle rear legs, seat slope. Three-second engineering drawings, joinery layout, cut list.",
    tagline: "Build a dining chair you'll happily sit in for two hours",
    subTagline: "Advanced template · back curve, splayed rear legs (compound angles), seat slope — all automatic",
    whatItDoes: "Dining chairs are woodworking's watershed project — plenty of people can build a stool; very few build a great chair. The difference: chairs need back rake (5–8° lean), splayed rear legs (so the chair doesn't tip when you lean back), seat slope (front-low-back-high, so you don't slide off), and tapered legs (visually light).\n\nThe algorithm bundles all four. Enter \"seat 45 cm, back 80 cm, 6° rake, rear-leg splay 8°\" and the system computes the rear-leg true length (with compound-angle math), back-slat spacing for 5 rails, and the joinery positions where each of the four legs meets the seat frame. The drawings ship with a back-curve detail, true-length leg dimensions, and table-saw setup values — cut to the lines and you get a chair you can sit in for two hours without lower-back pain.\n\nBuild 6 for a dining set, 1 for an office chair, 4 for a café — this template is the ceiling test for residential woodworking.",
    keywords: ["dining chair plans", "chair ergonomics", "splayed legs", "back rake angle", "DIY wooden chair"],
    fitFor: {
      good: ["Intermediate-to-advanced builders ready for \"real furniture\"", "Opening a café / B&B that needs 4–6 chairs", "Upgrading the dining-room atmosphere"],
      notFor: ["No mortise-and-tenon experience yet — build a stool first"],
    },
    parameters: [
      { label: "Seat / back height", desc: "Seat 42–45 cm, back 80–90 cm" },
      { label: "Back rake", desc: "5–8° is the comfort sweet spot; > 10° is not a dining chair" },
      { label: "Rear-leg splay", desc: "Usually 6–10°; prevents tipping when leaning back" },
      { label: "Back rails", desc: "3–7 horizontal rails; more rails = more visual mass" },
    ],
    scenarios: [
      { tag: "Dining set of six", body: "Build six identical chairs around a dining table — full set runs 50% less than IKEA at twice the quality." },
      { tag: "Café fit-out", body: "New shop needs 12 chairs; quotes come in at $260 each — your in-house material cost is $50 per chair." },
      { tag: "Home office", body: "A chair sized to your body — store-bought office chairs are universally too tall." },
      { tag: "Heirloom build", body: "Walnut dining chair that your kids will still use as adults — store-bought can't deliver that." },
    ],
    faqs: [
      { q: "What's the hardest part of a chair?", a: "The rear legs. They take body weight, lean-back load, and floor friction simultaneously. The algorithm cuts them to mm-precise length, but cut slowly and carefully." },
      { q: "Curved or straight back?", a: "Straight is easier; curved is more comfortable. First chair: straight. Second chair: gentle curve (R200–R300 radius)." },
      { q: "Do I have to upholster the seat?", a: "No. Finish the chair and send it to an upholsterer ($10–17 per chair) — cheaper and faster than doing it yourself." },
      { q: "Back-rail spacing?", a: "Ergonomic guidance: 5–7 rails, 5–8 cm spacing. Sparser = poor back support, denser = visually heavy. The template auto-spaces evenly based on rail count." },
      { q: "How long for 6 chairs?", a: "First one takes 2–3 working days (you're learning). Batch the next 5 — practiced hands can do one a day. Full set runs 2–3 weeks." },
    ],
    presets: [
      { name: "Straight-back, straight-leg", desc: "3 vertical back rails, square upright legs — the canonical dining chair, good for a first build." },
      { name: "Slat-back, splayed-leg", desc: "4 horizontal back rails with splayed rear legs — ergonomic, comfortable for long sits." },
      { name: "Windsor", desc: "Turned spindles in a fan back — English country / café classic, fine joinery." },
      { name: "Plank-back, tapered-leg", desc: "Single wide back panel with tapered legs — Hans Wegner Nordic feel, visually crisp." },
      { name: "Curved-back", desc: "Gentle bent back that hugs the spine — advanced bending work but a comfort upgrade." },
    ],
    howToSteps: [
      { name: "Mill stock precisely", text: "Cut front-leg, rear-leg, back-rail, and seat-rail stock. Rear legs need the compound-angle length from the drawings; cut both ends at the listed bevel." },
      { name: "Chop mortises", text: "Mark every mortise on front and rear legs from the three-view drawings. Chop with a 12 mm chisel — seat-rail mortises blind at 2/3 depth, back-rail mortises through." },
      { name: "Cut tenons and dry-fit", text: "Cut tenons on all rail ends, saw shoulders to the gauge line, pare to a slide-fit (no rocking, no daylight). Test every joint." },
      { name: "Dry-fit and verify three angles", text: "Assemble the full chair dry. Verify rear-leg rake, front/rear leg splay, and seat front-back slope with a bevel gauge or angle finder." },
      { name: "Glue-up in stages", text: "Glue the front frame, then the rear frame, then combine. Diagonal clamps at each stage, hold 24 h before releasing." },
      { name: "Sand and finish", text: "Sand 120 → 180 → 240 overall. Turn or file leg bottoms round to avoid catching carpet. Two coats of water-based PU for durability; upholster the seat if desired." },
    ],
    related: ["bar-stool", "bench", "stool"],
  },
  desk: {
    category: "desk",
    seoTitle: "Desk plans | Drawer / shelf / cable management — Wooden Ren Blueprint",
    seoDescription: "Build a desk that fits your monitor, keyboard and both hands. Auto drawer placement, shelf layout, cable port. Three-second engineering drawings, cut list, quote.",
    tagline: "A desk that actually fits you — better than IKEA",
    subTagline: "Advanced template · drawer / shelf / cable port / outlet channel — freely configurable",
    whatItDoes: "A desk is the most-bought piece of furniture in modern homes — but 80% of off-the-shelf desks are 110 cm wide × 75 cm tall × 60 cm deep. They never fit. If your corner is 145 cm wide, you want 72 cm tall (you're 168 cm), 55 cm deep (less light-blocking), the only option is to build it.\n\nThis desk template supports 1–3 drawers (left / right / center), 1–2 lower shelves, a 60 mm cable port at the rear, and an optional outlet-strip channel. Three base structures: 4 straight legs (most desk-like), 2 side panels with drawer carcase (sturdiest), A-frame (most material-efficient).\n\nKey size rule: desk height = your height / 4 + 5 cm. 168 cm tall → 47 cm desk height (chair included). 175 cm → 48–50 cm. The template suggests automatically from your height input.",
    keywords: ["desk plans", "office desk dimensions", "desk height", "DIY office desk", "work from home desk"],
    fitFor: {
      good: ["Working from home", "Family upgrading from a kid's desk to a teen's desk", "Studios / classrooms"],
      notFor: ["Want a height-adjustable desk (sit/stand frames sold separately; template doesn't include)", "No drill / saw and not going to a workshop", "Want to finish in a week as a beginner (the cable port + drawers add time)"],
    },
    parameters: [
      { label: "Top size", desc: "Recommended 120–160 cm wide × 55–70 cm deep" },
      { label: "Height", desc: "Auto-suggested from your height; warns if outside the comfort band" },
      { label: "Drawers", desc: "0–3 drawers, freely placed left / right / center" },
      { label: "Shelves", desc: "Add 1–2 lower shelves for keyboard tray or CPU" },
      { label: "Cable port", desc: "Optional 60 mm port at the top rear" },
    ],
    scenarios: [
      { tag: "Remote-work upgrade", body: "Three years on a folding desk — your back hurts. Build one sized to you." },
      { tag: "Kid desk", body: "Kid moving up to middle school needs a real desk — build 130 cm wide, finish with non-toxic oil." },
      { tag: "Studio desk", body: "Studio needs two identical desks; material cost runs ~50% of buying them." },
      { tag: "Corner fit", body: "Your bedroom has a 145 cm wide corner — store-bought desks won't fit. A custom build does." },
    ],
    faqs: [
      { q: "Standard desk height?", a: "No universal standard. 72–75 cm is typical retail, but < 165 cm tall = aim for 70 cm; > 175 cm = aim for 76 cm. The template suggests based on your input." },
      { q: "Do I need drawers?", a: "Depends on your workflow. Most remote workers actually don't (everything's on the laptop) — a plain top is cleaner. One drawer covers most stationery needs." },
      { q: "55 or 60 cm deep?", a: "Depends on monitor size. ≤ 24\" = 55 cm is enough (eye-to-screen 50 cm). ≥ 27\" = 60 cm so the screen isn't too close." },
      { q: "What top material?", a: "Veneered MDF is cheapest (~$25 / panel). Edge-glued solid wood has the best feel ($80–130 / panel). MDF + paint looks good but hates humidity. For desks, edge-glued solid wood — no regrets after 10 years." },
      { q: "Where do the cable ports go?", a: "Top rear, 10–15 cm in from each side. Rear is invisible from the front and within easy reach of the strip. 60 mm diameter clears an HDMI head." },
    ],
    presets: [
      { name: "Four straight legs, plain top", desc: "Most standard desk — no drawer or shelf — finishes in 2 days." },
      { name: "Side-panel with drawers", desc: "Right side has 2 drawers + a side panel — best for stationery-heavy users." },
      { name: "A-frame minimalist", desc: "Two A-frame side panels — minimum material, crisp visual, loft / industrial feel." },
      { name: "Cross-stretcher reinforced", desc: "Four legs + lower stretcher — handles heavy monitors and stacks of books." },
    ],
    howToSteps: [
      { name: "Mill and prep stock", text: "Mill leg, apron, and top stock to size + 5 mm allowance. Edge-glue tops > 40 cm wide. Square the ends." },
      { name: "Cut leg-apron joinery", text: "Chop apron mortises on legs (blind, 2/3 depth). Cut tenons on apron ends, pare to slide-fit." },
      { name: "Drawer carcase", text: "For drawer versions: cut dadoes for slide tracks, build the drawer box with dovetails or pocket-hole screws, leave 1.5 mm clearance around the drawer front." },
      { name: "Dry-fit", text: "Assemble the full desk dry. Try-square each corner; diagonals equal. Drill the 60 mm cable port with a Forstner bit." },
      { name: "Glue and attach top", text: "Glue the leg frame; attach the top from underneath with figure-8 fasteners or pocket-hole screws — leave expansion play so the top can move with humidity." },
      { name: "Sand and finish", text: "Sand 120 → 240. Two coats of water-based PU or hardwax oil; one extra coat on the top for wear. Light sand between coats." },
    ],
    related: ["dining-table", "side-table", "open-bookshelf"],
  },
  "open-bookshelf": {
    category: "open-bookshelf",
    seoTitle: "Open bookshelf plans | Shelf height by book type, sag check — Wooden Ren Blueprint",
    seoDescription: "Build a bookshelf that fits the books you actually own. Auto shelf height by book height, load + sag warnings. Three-second engineering drawings, joinery layout, cut list.",
    tagline: "Build a shelf where your books actually fit",
    subTagline: "Shelf height auto-tuned to book height — paperbacks / A4 / art books all sized in",
    whatItDoes: "90% of retail bookshelves have a fixed 30 cm shelf height — but your books aren't sorted that way. Manga is 17 cm, paperbacks 15 cm, A4 books 30 cm, art books / photography 35 cm. A flat 30 cm shelf either won't hold them or wastes half the shelf above.\n\nThis template lets you enter each shelf's height (manga shelf 18 cm, paperback 16 cm, A4 32 cm, top 38 cm). The system places the shelves, totals the height, and flags stability concerns. A bookshelf isn't about looking nice — it's about books actually fitting.\n\nStructurally: fixed shelves (sturdiest), adjustable pins (32 mm euro hole pattern), or hybrid (fixed in the front half, adjustable in the back). Recommended depth 22–26 cm (paperback + A4), and 30–40 cm per opening (wider than that, shelves start to sag). A wall-to-wall built-in book wall runs $2000–3000 retail; the same wall in material is $500–1000. You finish it knowing every board, every joint — that's not something a store-bought delivers.",
    keywords: ["bookshelf plans", "open bookcase", "shelf height book", "library shelf DIY", "bookshelf dimensions"],
    fitFor: {
      good: ["Big book collection with mixed heights", "Want a wall-fitted built-in", "Practicing case construction"],
      notFor: ["Fewer than 50 books — buy IKEA BILLY", "Rental with no permitted wall fixings (tall shelves need wall anchors)", "Wanting glass-door display — use the display-cabinet template"],
    },
    parameters: [
      { label: "Tiers / heights", desc: "1–6 tiers, each height independently set" },
      { label: "W / D / total H", desc: "Single bay 30–40 cm wide (avoid sag), 22–26 cm deep" },
      { label: "Shelf thickness", desc: "18 mm minimum; > 60 cm spans want 21 mm" },
      { label: "Fixed vs adjustable", desc: "Fixed = sturdiest; adjustable = swap shelf heights as your collection changes" },
    ],
    scenarios: [
      { tag: "Serious collector", body: "2,000 books, off-the-shelf bookshelves don't fit the mix of heights — only a custom build does." },
      { tag: "Built-in wall", body: "Living-room wall 250 cm wide — full-wall built-in saves $1,500 over hiring a carpenter." },
      { tag: "Artist's studio", body: "Art and photography books vary 20–35 cm; only a custom shelf layout actually accommodates them." },
      { tag: "First built-in", body: "First major build in a new house — a wall-fit bookshelf marks the house as yours." },
    ],
    faqs: [
      { q: "Will the shelves sag?", a: "Depends on width × thickness. 18 mm board across a 60 cm span sags 1–2 mm under load. Over 70 cm span, move to 21 mm or add a center support. The algorithm warns when geometry is risky." },
      { q: "Do I need a back panel?", a: "If wall-mounted, you can skip it. Free-standing — add a 9 mm thin back panel; cleaner look and books can't push through and jam against the wall." },
      { q: "Are adjustable shelves hard?", a: "Easy. Drill a row of 5 mm holes at 32 mm spacing (the European standard) on each side panel. Buy shelf pins from any hardware store. The template gives you the hole layout." },
      { q: "Must the bookshelf be anchored?", a: "Yes. Any shelf > 130 cm tall, fully loaded, easily exceeds 100 kg. Earthquake-zone fixings (L-bracket into the wall stud) are non-negotiable for safety." },
      { q: "Back panel thickness?", a: "9 mm plywood is plenty (back panel doesn't carry load). 6 mm if material is tight, but it'll look thin. For a built-in flush to a tiled wall, you can skip the back panel entirely." },
    ],
    presets: [
      { name: "Fixed shelves classic", desc: "All fixed shelves at custom heights — set once, stays put, no wobble." },
      { name: "Adjustable pins", desc: "32 mm euro-spaced shelf-pin holes — change shelf heights as the collection evolves." },
      { name: "Drawers on bottom", desc: "Bottom tier converts to drawers for non-book storage; upper tiers for shelves." },
      { name: "Vertical dividers", desc: "Add vertical dividers between shelf sections — keeps books standing, adds visual rhythm." },
      { name: "Wall-to-ceiling built-in", desc: "Sides flush to the wall, top flush to the ceiling — the wall-of-books look you can't buy off the shelf." },
    ],
    howToSteps: [
      { name: "Mill stock", text: "Cut side, top/bottom, and shelf stock. Use 21 mm if any span > 60 cm. Add an apron strip below shelves over 70 cm to prevent sag." },
      { name: "Adjustable holes or fixed dadoes", text: "Fixed-shelf version: chop dadoes (8 mm deep) on the inside of each side panel. Adjustable: drill a row of 5 mm holes at 32 mm spacing — perfectly vertical." },
      { name: "Assemble the carcase", text: "Join top, bottom, and sides via mortise-and-tenon or pocket-hole screws. Check square at each corner. Slot the back panel into a rabbet or pin it in place." },
      { name: "Install shelves", text: "Fixed shelves: glue into the dadoes + screw through the side from outside for reinforcement. Adjustable shelves: insert shelf pins, drop in the boards." },
      { name: "Anchor and sand", text: "Anchor the top to the wall studs with L-brackets (mandatory in seismic regions). Sand 120 → 240 overall." },
      { name: "Finish", text: "Two coats of water-based PU. Don't skip the back or edges. Light sand at 400 grit between the second and third coat for a tactile finish." },
    ],
    related: ["wardrobe", "media-console", "shoe-cabinet"],
  },
  "dining-table": {
    category: "dining-table",
    seoTitle: "Dining table plans | 6–10 seat, edge-glue, leg style — Wooden Ren Blueprint",
    seoDescription: "Build the dining table the whole family gathers around. Auto edge-glue layout, leg geometry, span / load check. Three-second engineering drawings, cut list, quote.",
    tagline: "Build the table your family will eat around",
    subTagline: "Advanced template · edge-glued top, four straight / A-frame / trapezoid legs",
    whatItDoes: "The dining table is the piece of furniture that holds the family's memory — kids' homework, teenage fights, wedding dinners. Most retail dining tables are 75–85 cm wide (fine for two-up), but if your family hosts 6–8 people, you need 90–100 cm — and that's where DIY starts winning.\n\nThis template auto-handles edge-glue (any board wider than 30–40 cm gets multiplane'd, and tongue-and-groove positions are computed for you), three leg styles (four straight, A-frame, trapezoid), and an optional skirting (cleaner look or open underside). Lengths over 180 cm auto-add a center support leg to prevent sag.\n\nA real hardwood dining table retails for $1,500–3,000. Material (oak edge-glued top + leg stock) is typically $150–300. More importantly — this table can have your initials carved in, dimensioned exactly to your dining room, used for 30 years, and the kids will remember who built it.",
    keywords: ["dining table plans", "dining table dimensions", "edge-glued top", "DIY dining table", "solid wood table"],
    fitFor: {
      good: ["Building heirloom furniture", "Hosts large groups regularly", "Practicing large-panel edge-gluing"],
      notFor: ["No table saw / rip fence (edge-gluing needs straight clean edges)", "Workshop too small to swing 200 cm of stock", "Want to finish in a week — edge-glue alone needs 24 h per stage"],
    },
    parameters: [
      { label: "L × W", desc: "4-seat 140×80, 6-seat 180×85, 8-seat 220×90" },
      { label: "Height", desc: "Standard 72–75 cm; bar height 90–95 cm" },
      { label: "Edge-glue", desc: "> 40 cm wide auto-splits; tongue-and-groove or biscuit or dovetail joinery" },
      { label: "Leg style", desc: "Four straight (traditional) / A-frame (sturdiest) / trapezoid (Nordic)" },
    ],
    scenarios: [
      { tag: "Heirloom", body: "Walnut table that three generations will eat around — store-bought can't match the meaning." },
      { tag: "Host life", body: "Friend circle loves to gather; restaurants close too early. Build a real 8-seat table in oak for $300." },
      { tag: "Café fit-out", body: "New café needs 4–6 tables — quote is $500 each; in-house material cost is $130 per table." },
      { tag: "Newlywed first build", body: "First piece in the new home — built together start to finish. Every dinner afterward sits at that table." },
    ],
    faqs: [
      { q: "Will the edge-glue crack down the middle?", a: "Not if the joinery and species are right. Cypress / oak / maple shrink 0.1–0.2% along grain, so 200 cm = 2–4 mm — a designed expansion gap absorbs that. Avoid pine (too much movement)." },
      { q: "Does a dining table need a skirt?", a: "Optional. Skirt = tidy, hides edges; no skirt = top reads larger and more modern. Style call." },
      { q: "How do I maintain it?", a: "Oil finish (linseed / Danish oil): refresh every 6 months — most natural feel. Water-based PU: one-and-done for 5 years but no oil feel. Personal choice." },
      { q: "How many boards in the edge-glue?", a: "Top 90 cm wide ÷ 25 cm per board = 4 boards. Fewer boards = cleaner; wider boards = more cupping risk. Oak or maple at 20–25 cm per board is the safe band." },
      { q: "How thick should the legs be?", a: "Square legs: minimum 60 × 60 mm. Round legs: minimum 50 mm diameter. Anything thinner wobbles on a 180 cm-long table. The algorithm warns based on top weight." },
    ],
    presets: [
      { name: "Four straight legs", desc: "60 × 60 mm legs, classic dining-table proportions, 180 cm × 6-seat — the canonical first build." },
      { name: "A-frame sturdy", desc: "Two A-frame sides with mid-stretcher — best load-bearing, industrial visual." },
      { name: "Drop-leaf", desc: "Hinged sides fold down — 120 cm closed, extends to 160 cm for guests — perfect for small homes." },
      { name: "Cross-stretcher full joinery", desc: "Four legs + four-side lower stretcher — all mortise-and-tenon, heirloom-grade craft." },
    ],
    howToSteps: [
      { name: "Edge-glue the top", text: "Tops > 40 cm wide require an edge-glue. Cut planks 20–25 cm wide, plane to identical thickness, joint mating edges square. Tongue-and-groove or biscuit the joint, glue, parallel-clamp 24 h before releasing." },
      { name: "Legs and aprons", text: "Mortise the legs for the aprons; cut apron tenons. For A-frame builds, cut the side panels with the leg-splay angle from the drawings." },
      { name: "Dry-fit", text: "Assemble the full table dry. Squared corners, equal diagonals, even floor footprint. Tables > 160 cm add a center support leg and verify it sits flat." },
      { name: "Glue-up", text: "Glue the leg/apron frame first, then attach the top. Top attaches via figure-8 fasteners or pocket-hole screws from below, with 3 mm expansion play." },
      { name: "Sand and final flatten", text: "Sand 80 → 120 → 180 → 240. Pay attention to the edge-glue seams — any face misalignment removed with a card scraper or hand plane." },
      { name: "Finish", text: "Two to three coats of Danish oil or hardwax oil, 4 hours between coats. Wait 3 full days before serving food on the surface so the finish fully cures." },
    ],
    related: ["dining-chair", "round-table", "desk"],
  },
  "tea-table": {
    category: "tea-table",
    seoTitle: "Coffee table plans | Living-room, lower shelf, drawer — Wooden Ren Blueprint",
    seoDescription: "Build a coffee table sized to your sofa. Lower shelf for magazines, drawer for remotes. Three-second engineering drawings, cut list, quote.",
    tagline: "The right-sized coffee table for the sofa you actually have",
    subTagline: "Intermediate template · plain-top / lower-shelf / drawer variants",
    whatItDoes: "The coffee table is the visual center of the living room — it's the first thing you see from the sofa. Off-the-shelf coffee tables are either too big (covers the whole rug) or too low (awkward mug reach).\n\nThe template suggests size based on your sofa width (coffee-table width = 50–70% of sofa width) and height (5 cm below sofa seat is the mug sweet spot). Lower-shelf version stores magazines, remotes, board games; drawer version hides cables and remotes. Three leg styles: straight, X-cross, single-slab carved.\n\nMaterial cost ~$50–100 (solid wood top + legs) — twice the lumber quality of an IKEA LACK, at the same overall cost, sized for your room. After this build you'll have nailed \"flat top + leg attachment\" — the same logic applies to dining tables and desks at larger scale.",
    keywords: ["coffee table plans", "living room coffee table", "coffee table dimensions", "DIY coffee table", "solid wood coffee table"],
    fitFor: {
      good: ["Furnishing a new living room", "Upgrading the room's character", "Learning intermediate table-class joinery"],
      notFor: ["Want a marble or glass top (template is wood)", "Less than 80 cm of clear space in front of the sofa", "Want a folding mechanism — sold separately"],
    },
    parameters: [
      { label: "L × W", desc: "Sofa width × 0.5–0.7, depth 50–60 cm" },
      { label: "Height", desc: "Sofa seat height − 5 cm (best mug reach)" },
      { label: "Lower shelf", desc: "Optional; great for magazine storage" },
      { label: "Drawer", desc: "0–2 drawers; hides remotes / cables" },
    ],
    scenarios: [
      { tag: "New living room", body: "Sofa 200 cm wide — store-bought coffee tables read too big. Build 130 × 55 × 38 — fits exactly." },
      { tag: "Housewarming gift", body: "Friends just moved in; engrave a coffee table and gift it — beats cash by a wide margin." },
      { tag: "Tea-ceremony floor mat", body: "Practicing tea ceremony needs a low coffee table (cushion-floor seating); store-bought options are almost nonexistent." },
      { tag: "Rental upgrade", body: "A hand-built coffee table in a rental instantly turns 'landlord furniture' into 'your style'." },
    ],
    faqs: [
      { q: "How do I pick the height?", a: "5–10 cm below sofa seat is the sweet spot. Sofa seat 42 cm → coffee table 32–37 cm. Sit on your actual sofa and measure." },
      { q: "Need a lower shelf?", a: "If you tend to leave magazines / remotes out — yes. Plain top reads cleaner. Style call." },
      { q: "Will it slide around?", a: "Solid 18 mm top × 130 cm wide weighs 15–20 kg — doesn't slide in normal use. Kids riding on it — different story." },
      { q: "Are X-cross legs hard?", a: "One extra bevel per leg, and each crossing leg needs a half-lap on the diagonal. The algorithm gives bevel + lap-depth values; cutting just needs patience." },
      { q: "Chamfer the top edge?", a: "Yes. 3–5 mm chamfer (R radius or 45° bevel) on the top edge — won't bruise hands, looks crisper. Five minutes with a hand plane or trim router." },
    ],
    presets: [
      { name: "Straight-leg plain top", desc: "Fastest build — four straight legs + a top, visually minimal in front of the sofa." },
      { name: "Lower-shelf magazine", desc: "Add a lower shelf for magazines and remotes — most practical living-room layout." },
      { name: "X-cross leg", desc: "X-cross legs with a wide top — Nordic living-room signature, visually light and designerly." },
      { name: "Drop-leaf", desc: "Drop-down side leaves — compact for daily use, expands when guests arrive." },
    ],
    howToSteps: [
      { name: "Mill stock", text: "Cut leg, apron, top stock to size + 3 mm. Table-saw to final, square the ends." },
      { name: "Joinery", text: "Mortise legs for blind apron tenons (2/3 thickness). Cut apron tenons. X-cross legs: half-lap each pair where they cross." },
      { name: "Dry-fit", text: "Assemble dry. All four feet sit flat, diagonals equal. Drop-leaf builds: test the leaves fold without interference." },
      { name: "Glue-up", text: "Glue the leg frame; attach the top via figure-8 fasteners from underneath, leaving 2 mm of expansion play. 24 h cure." },
      { name: "Sand and finish", text: "Sand 120 → 240. Chamfer or radius the top edges at 5 mm. Two coats of Danish oil — silky finish." },
    ],
    related: ["side-table", "low-table", "round-tea-table"],
  },
} satisfies Record<string, TemplateMarketing>;

export const TEMPLATE_MARKETING_EN: Record<string, TemplateMarketing> = M_EN;

export const FEATURED_TEMPLATE_CATEGORIES_EN = Object.keys(M_EN) as FurnitureCategory[];
