/**
 * spec.label 英文翻譯字典 — 用 spec.key 當主鍵，跨 26 個 template 共享。
 *
 * 為什麼不直接改 template 檔的 label：26 支 template × 平均 20 個 spec ≈ 500 個
 * 字串散布在 17K 行 code 內，硬塞 nameEn/labelEn 改動量過大、出錯機率高。
 * 改在 render layer 攔截，spec.label 維持 zh，多開一份 zh→en map。
 *
 * Coverage 策略：先涵蓋出現在 ≥3 個 template 的高頻 key（~100 個），長尾少見
 * key 直接 fallback 回 spec.label（zh）。未來補譯只要往這檔加 key 即可。
 *
 * 用法：`specLabel(spec, locale)` — locale='en' 且 key 在表內 → 回英文；
 * 其他情況都回 spec.label。
 *
 * 維護紀律：新增 template 或新 key 時，常用 key 同步加進來。
 * 對齊譯詞表（之後建）：docs/glossary-zh-en.md
 */

import type { OptionSpec } from "@/lib/types";

export const SPEC_LABEL_EN: Record<string, string> = {
  // === Legs ===
  legShape: "Leg shape",
  legSize: "Leg size",
  legWidth: "Leg width X",
  legDepth: "Leg depth Z",
  legHeight: "Leg height",
  legInset: "Leg inset",
  legEdge: "Leg edge size",
  legWidthOverride: "Leg width override",
  legDepthOverride: "Leg depth override",
  legPenetratingTenon: "Through tenons (decorative)",
  splayAngle: "Splay angle (°)",
  withLegs: "🦿 With legs",
  withFootboard: "With footboard",

  // === Top / Seat ===
  topType: "Top type",
  topThickness: "Top thickness",
  seatThickness: "Seat thickness",
  seatEdge: "Edge size",
  seatEdgeStyle: "Edge profile",
  seatEdgeBottom: "Bottom edge size",
  seatProfile: "Seat scoop",
  topPanelPieces: "Top board glue-up",
  backRake: "Back rake (°)",
  seatBendMm: "Seat dish",
  seatCornerR: "Seat corner radius",
  seatPenetratingTenon: "Through-seat tenon (legs visible on top)",

  // === Apron ===
  apronWidth: "Apron height",
  apronThickness: "Apron thickness",
  apronDropFromTop: "Apron drop from top",
  apronOffset: "Apron offset",
  apronStaggerMm: "Apron stagger",
  apronEdge: "Apron edge size",
  apronEdgeStyle: "Apron edge profile",
  withApron: "With apron",
  spandrelStyle: "Spandrel style",
  friezePanel: "Frieze panel",

  // === Stretchers ===
  withLowerStretcher: "Add lower stretcher",
  withLowerStretchers: "Add lower stretchers",
  withCenterStretcher: "Add center stretcher",
  withUnderShelf: "Under-seat shelf",
  lowerStretcherStyle: "Lower stretcher style",
  lowerStretcherWidth: "Lower stretcher height",
  lowerStretcherThickness: "Lower stretcher thickness",
  lowerStretcherHeight: "Lower stretcher floor height",
  lowerStretcherStaggerMm: "Lower stretcher stagger",
  lowerStretcherArrangement: "Lower stretcher layout",
  stretcherStyle: "Stretcher style",
  stretcherEdge: "Stretcher edge size",
  stretcherEdgeStyle: "Stretcher edge profile",
  standingBraceStyle: "Standing brace style",

  // === Back / chair-specific ===
  backStyle: "Back style",
  backHeight: "Back height",
  backInsetFromEndMm: "Back inset from seat end",
  backInsetFromRearMm: "Back inset from seat rear",
  endSplat: "End splat",
  withArmrest: "With armrest",
  armrestHeight: "Armrest height",
  armrestPlankWidth: "Armrest plank width",
  armrestPlankThickness: "Armrest plank thickness",
  armrestPostWidth: "Armrest front post X",
  armrestPostThickness: "Armrest front post Z",
  rearPostMode: "Rear post mode",
  headStyle: "Headboard style",

  // === Carcase / panels ===
  panelThickness: "Panel thickness",
  bottomThickness: "Bottom panel thickness",
  bottomType: "Bottom panel type",
  bottomAttach: "Bottom panel attachment",
  pedestalTopAttach: "Pedestal-top attachment",
  wallThickness: "Wall thickness",
  cabinetCorner: "Cabinet corner",
  cornerJoinery: "Corner joinery",
  bodyShape: "Body shape",
  boxShape: "Box shape",
  panelStyle: "Panel style",

  // === Layout / zones / columns ===
  layoutMode: "Layout mode",
  compoundMode: "Compound mode",
  layerCount: "Number of tiers",
  layer1Type: "Tier 1 type",
  layer2Type: "Tier 2 type",
  layer3Type: "Tier 3 type",
  layer4Type: "Tier 4 type",
  layer5Type: "Tier 5 type",
  layer6Type: "Tier 6 type",
  layer7Type: "Tier 7 type",
  layer8Type: "Tier 8 type",
  upperType: "Upper zone type",
  midType: "Mid zone type",
  bottomType_zone: "Lower zone type",
  withUpperZone: "Add upper zone",
  leftType: "Left column type",
  rightType: "Right column type",
  centerType: "Center column type",
  leftCount: "Left column rows",
  rightCount: "Right column rows",
  centerCount: "Center column rows",
  left: "Left column",
  right: "Right column",
  front: "Front",
  back: "Back",
  verticalDividerCount: "Vertical divider count",
  dividerThickness: "Divider thickness",
  dividerHeight: "Divider height",
  polygonDividerStyle: "Polygon divider style",
  gridLayout: "Grid layout",

  // === Drawers ===
  withDrawer: "With drawer",
  withPullOutDrawer: "With pull-out drawer",
  drawerCount: "Drawer count",
  drawerRows: "Drawer rows",
  drawerStyle: "Drawer style",
  drawerSide: "Drawer side",
  drawerFaceStyle: "Drawer face style",
  drawerBackMode: "Drawer back mode",
  drawerHeightStyle: "Drawer height style",
  ascendingDrawerCount: "Total drawer count",
  apronDrawerPosition: "Apron-drawer position",
  apronDrawerWidth: "Apron-drawer width",
  apronDrawerFrontInset: "Drawer front inset",

  // === Doors / handles / hardware ===
  doorType: "Door type",
  doorStyle: "Door style",
  withHandle: "With pulls",
  handleShape: "Pull shape",
  pullStyle: "Pull style",
  withLid: "With lid",
  lidType: "Lid type",

  // === Misc structure ===
  hasLowerShelf: "Add lower shelf",
  withSlatRack: "Add slat rack",
  withGalleryRail: "Add gallery rail",
  withLedderRail: "Add ladder-back rail",
  withBookStop: "Add book stop",
  withLazySusan: "Add lazy Susan",
  withToeKick: "Add toe kick",
  withCrownMolding: "Add crown molding",
  withGrooveBack: "Add grooved back panel",
  withRebate: "Add rebate",
  dropLeaf: "Drop leaf",
  liveEdge: "Live edge",
  lockTotalHeight: "🔒 Lock total height",
  sizingMode: "Sizing mode",
  useCase: "Use case",
  balustradeStyle: "Balustrade style",
  angledRack: "Angled shoe shelves",
  angledRackTilt: "Angle (°)",

  // === Tier-2 long-tail (deduplicated against the main map above) ===
  backPanelBottomArch: "Bottom-edge arch rise",
  backPanelCornerR: "Curved panel corner radius",
  backPanelEmbed: "Backrest cylinder embed depth",
  backPanelFaceBend: "Curved panel face bend",
  backPanelHeight: "Back panel height",
  backPanelInset: "Back panel inset",
  backPanelMaterial: "Back panel material",
  leftWidthMm: "Left column width",
  rightWidthMm: "Right column width",
  singleLayerLeftWidthMm: "Left column width",
  singleLayerRightWidthMm: "Right column width",
  legEdgeStyle: "Leg edge profile",
  pedestalTopGap: "Pedestal-top gap",
  pedestalStretcherHeight: "Pedestal stretcher floor height",
  headHeight: "Headboard height",
  wallHeight: "Ceiling height",
  ceilingHeight: "Ceiling height",
  withFrenchCleat: "Add French cleat",

  // Round-table / lazy-susan / center stretcher
  withLazySusanBearing: "Lazy Susan bearing",
  withTrim: "Add trim molding",
  withMolding: "Add molding",

  // Box / dovetail-box detail
  segmentCount: "Segment count",
  angleDeg: "Angle (°)",
  insideDimsMode: "Inside-dim mode",

  // Coat rack
  hookCount: "Hook count",
  hookHeight: "Hook height",

  // Bed
  mattressLength: "Mattress length",
  mattressWidth: "Mattress width",
  slatCount: "Slat count",

  // === Bench / bar-stool / dining-chair back family ===
  slatSize: "Slat size",
  slatWidth: "Slat width",
  topRailSize: "Top rail size",
  topRailThickness: "Top rail thickness",
  topRailHeight: "Top rail height",
  backTopRailHeight: "Top rail height (backrest)",
  slatBackInset: "Slat back inset",
  slatEndInset: "Slat end inset",
  topRailBendMm: "Top rail back-bend",
  ladderRungs: "Ladder rungs",
  ladderRailH: "Ladder rail height",
  ladderRailT: "Ladder rail thickness",
  ladderRailGap: "Ladder rail gap",
  ladderRailBendMm: "Ladder rail back-bend",
  windsorSpindleCount: "Windsor spindle count",
  windsorPostD: "Windsor post diameter",
  windsorSpindleD: "Windsor spindle diameter",
  windsorRakeDeg: "Windsor back rake angle",
  windsorBowBendMm: "Windsor bow bend",
  windsorTopRailH: "Windsor top rail width",
  windsorTopRailT: "Windsor top rail thickness",
  windsorBackInset: "Windsor back inset from rear",
  windsorEndInset: "Windsor back inset from ends",
  windsorHeight: "Windsor backrest height",
  backPanelThickness: "Panel back thickness",
  backPanelTopArch: "Top edge arch",
  backPostDiameter: "Round support post diameter",
  backReclineDeg: "Back recline angle",
  backPostFromEdge: "Post distance from end face",
  backSlats: "Slat count",
  backSlatWidth: "Slat width",
  backSlatThickness: "Slat thickness",
  backRailInsetZ: "Support post distance from seat rear",
  backRailInsetX: "Support post distance from seat end",
  backRailPostWidth: "Support post width X",
  backRailPostThickness: "Support post thickness Z",
  footrestWidth: "Footrest width",
  footrestThickness: "Footrest thickness",
  footrestStaggerMm: "Footrest stagger",
  seatHeight: "Seat height",
  seatFrontWaterfall: "Front-edge waterfall",
  splatWidth: "Splat width",
  curvedSplatWidth: "Curved splat width",
  curvedSplatBendMm: "Curved splat bend",
  // ── Phase 4 batch:181 漏譯 OptionSpec 補完 ──
  backMode: "Back panel mode",
  backPanelPlywood: "Back uses plywood (cost-saver)",
  backPanelStyle: "Back panel style",
  backThickness: "Back thickness",
  backTopRailThickness: "Back top rail thickness",
  balustradeHeight: "Gallery rail height",
  bedPreset: "Style preset",
  bookStopHeight: "Bookstop height",
  bookStopThickness: "Bookstop thickness",
  bottleDiameter: "Bottle diameter",
  bottleOrientation: "Bottle orientation",
  bottlesTall: "Bottles vertical",
  bottlesWide: "Bottles horizontal",
  bottleType: "Bottle type preset",
  bottomHeight: "Bottom section height",
  boxUse: "Use case preset",
  brassPillarInset: "Brass pillar inset",
  cabinetPreset: "Configuration preset",
  capOverhangExtra: "Cap overhang extra",
  centerDoorCols: "Door horizontal divisions",
  centerDoorInnerShelves: "Inner shelves behind door",
  centerDrawerCols: "Drawer horizontal divisions",
  centerDrawerRowRatio: "Drawer row ratio (≥2 rows)",
  centerShelvesCols: "Open shelf horizontal divisions",
  centerStretcherDrop: "Stretcher drop from apron",
  centerStretcherThickness: "Center stretcher thickness",
  centerStretcherWidth: "Center stretcher height",
  chamferMm: "Chamfer size",
  columnSize: "Column size",
  columnStyle: "Column style",
  corniceDepth: "Cornice thickness",
  corniceHeight: "Cornice height",
  corniceOverhang: "Cornice overhang",
  crossDividers: "Cross dividers",
  crownProjection: "Crown projection",
  dividerInset: "Divider groove depth",
  dividers: "Vertical dividers",
  doorFrameRailWidth: "Door frame rail width",
  doorFrameThickness: "Door frame thickness",
  doorGap: "Door center gap",
  doorMullion: "Glass door mullion",
  doorPullStyle: "Door pull style",
  doorPullType: "Door pull type",
  dovetailAngle: "Dovetail angle (°)",
  dovetailSegments: "Dovetails per corner",
  drawerBackThickness: "Drawer back thickness",
  drawerBottomMode: "Drawer bottom mode",
  drawerBottomThickness: "Drawer bottom thickness",
  drawerBoxJoinery: "Drawer box joinery",
  drawerCols: "Lower drawer columns",
  drawerDepth: "Drawer depth",
  drawerFaceOffset: "Face offset from front",
  drawerHeight: "Lower drawer zone height",
  drawerInternalGrid: "Drawer internal grid",
  drawerMount: "Drawer face mounting",
  drawerPullStyle: "Drawer pull style",
  drawerPullType: "Drawer pull type",
  drawerRowRatio: "Drawer row ratio (≥2 rows)",
  drawerSlideType: "Drawer slide type",
  drawerSplit: "Drawer split",
  drawerZoneHeight: "Drawer zone total height",
  dropLeafWidth: "Drop-leaf width",
  edgeChamfer: "Column edge chamfer",
  fingerSegments: "Finger joint segments",
  footboardHeight: "Footboard height",
  footboardThickness: "Footboard thickness",
  footCount: "Foot claw count",
  footLength: "Foot claw length",
  footrestHeight: "Footrest height",
  frameProfile: "Frame profile",
  frameThickness: "Frame thickness",
  frameWidth: "Frame width",
  friezeHeight: "Frieze panel height",
  galleryInset: "Gallery inset",
  glassGrooveDepth: "Glass groove depth",
  glassThickness: "Glass thickness",
  handleHeight: "Handle hole height",
  handleTopMargin: "Handle margin from top",
  handleWidth: "Handle hole width",
  headboardHeight: "Headboard height",
  headboardThickness: "Headboard thickness",
  headSpindleCount: "Headboard spindle count",
  headSpindleSize: "Headboard spindle size",
  hiddenDrawerLayer: "Hidden drawer layer",
  hoofMm: "Hoof height",
  hoofScale: "Hoof splay multiplier",
  hookLength: "Hook projection length",
  layer1HeightMm: "Layer 1 height",
  layer2HeightMm: "Layer 2 height",
  layer3HeightMm: "Layer 3 height",
  layer4HeightMm: "Layer 4 height",
  layer5HeightMm: "Layer 5 height",
  layer6HeightMm: "Layer 6 height",
  layer7HeightMm: "Layer 7 height",
  layer8HeightMm: "Layer 8 height",
  lazySusanDiameter: "Lazy susan diameter",
  ledgerThicknessMm: "Ledger thickness",
  ledgerWidthMm: "Ledger width",
  leftDoorCols: "Door horizontal divisions",
  leftDoorInnerShelves: "Inner shelves behind door",
  leftDrawerCols: "Drawer horizontal divisions",
  leftDrawerRowRatio: "Drawer row ratio (≥2 rows)",
  leftShelvesCols: "Open shelf horizontal divisions",
  lidThickness: "Lid thickness",
  liftOffLidH: "Lift-off lid height",
  lowerHeight: "Lower section height",
  lowerShelfThickness: "Lower shelf thickness",
  lowerStretcherDoubleRailGap: "Double-rail gap (lower stretcher)",
  lowerStretcherFromGround: "Lower stretcher height from ground",
  mattressClearanceMm: "Mattress clearance height",
  midHeight: "Mid section height",
  mountType: "Mounting type",
  panelInlay: "Panel inlay",
  pedestalDepth: "Pedestal depth",
  pedestalFootLength: "Foot claw length",
  pedestalFootThickness: "Foot claw thickness",
  pedestalFootWidth: "Foot claw width",
  postEndStyle: "Post top style",
  postSize: "Post size",
  proportionStyle: "Proportion style",
  pullPosition: "Pull position",
  rackStyle: "Style preset",
  railThickness: "Side rail thickness",
  railWidth: "Side rail width",
  reinforcementHeight: "Reinforcement height",
  reinforcementPosition: "Reinforcement position",
  reinforcementThickness: "Reinforcement thickness",
  rightDoorCols: "Door horizontal divisions",
  rightDoorInnerShelves: "Inner shelves behind door",
  rightDrawerCols: "Drawer horizontal divisions",
  rightDrawerRowRatio: "Drawer row ratio (≥2 rows)",
  rightShelvesCols: "Open shelf horizontal divisions",
  shelfExtraCount: "Extra adjustable shelves",
  shelfOrientation: "Lower slat direction",
  shelfSlatEdge: "Lower slat edge",
  shelfSlatEdgeStyle: "Lower slat edge style",
  shelfSlatThickness: "Lower slat thickness",
  shelfSlatWidth: "Lower slat width",
  sideRailThickness: "Side rail thickness",
  sideRailWidth: "Side rail height",
  singleLayerCols: "Horizontal columns (upper)",
  skirtHeight: "Apron height",
  skirtStyle: "Apron style",
  skirtThickness: "Apron thickness",
  slatGapMm: "Slat gap",
  slatThickness: "Slat thickness",
  slatThicknessMm: "Bed slat thickness",
  slatWidthMm: "Bed slat width",
  slidingLidStyle: "Sliding lid style",
  spandrelSize: "Spandrel size",
  standingBraceSize: "Standing brace size",
  toeKickHeight: "Toe kick height",
  toeKickRecess: "Toe kick recess",
  topBoxLayers: "Top box layers",
  topBoxRatio: "Top box height ratio",
  topCols: "Drawer columns (split L/R)",
  topCount: "Door count",
  topDecor: "Top decoration style",
  topDoorShelves: "Inner shelves behind upper door",
  topOverhang: "Top overhang",
  totalLength: "Total length",
  upperApronThickness: "Apron thickness",
  upperApronWidth: "Apron height",
  upperCols: "Upper columns (split L/R)",
  upperCount: "Upper count (shelves / doors)",
  upperDoorShelves: "Inner shelves behind upper door",
  upperHeight: "Upper section height",
  useDrawerSlide: "Three-section slides (12.5 mm each side)",
  wallMode: "Wall-side mode (no back hooks)",
  wallSplay: "Wall splay angle (°)",
  withBrace: "Triangle reinforcement",
  withFloorTray: "Floor shoe tray",
  withHatRail: "Top hat rail",
  withHFrame: "H-frame stretcher",
  withInnerTray: "Removable inner tray",
  withLowerShelf: "Lower round shelf",
  withMirror: "Mid-section mirror",
  withModestyPanel: "Modesty panel",
  withSecondHookRow: "Second hook row",
  withShelfReinforcement: "Shelf reinforcement rail",
  withUmbrellaBase: "Umbrella base slot",
};

/**
 * spec.help EN map. Long-tail; only the most-commonly-hovered tooltips translated.
 * Missing → falls back to spec.help (zh).
 */
export const SPEC_HELP_EN: Record<string, string> = {
  legInset: "Distance from leg center to seat edge. > 0 makes the top overhang the legs — crisper visual.",
  splayAngle: "Splay angle relative to vertical, in the splayed-leg family. Default ~3° is mild; 10°+ reads boldly (Nordic), max ~15°.",
  legPenetratingTenon: "Checked: apron / stretcher tenons go all the way through the leg (Ming-style decorative). Unchecked: blind tenon at 2/3 mother thickness.",
  seatPenetratingTenon: "Checked: leg-top tenon passes through the seat (visible end-grain — traditional). Unchecked: blind tenon at ≤ 4/5 seat thickness.",
  withLowerStretcher: "Adds a stretcher ring at the lower 1/4 of leg height — significantly stiffer; classic four-leg stool detail.",
  lowerStretcherHeight: "0 = auto (22% of leg height).",
  lowerStretcherStaggerMm: "How much the left/right lower stretchers ride above the front/back pair. 0 = even-height (auto half-lap to avoid clash).",
  apronDropFromTop: "Distance from apron's top face down to the seat's bottom edge. Small stools should leave a slim gap (~3/8–5/8 in / 10–15 mm) so it doesn't look top-heavy.",
  apronStaggerMm: "How much the front/back aprons drop relative to the left/right pair. 0 = even-height (auto half-lap to avoid clash).",
  lockTotalHeight: "Locked: total height is fixed; remaining height after each tier becomes the leg, with a minimum threshold (~1-1/4 in / 30 mm; warning shown if smaller). Unlocked: legs are set directly, lower zone fills remainder.",
  seatBendMm: "Whole seat bends like a laminated panel — center dips for comfort; corner mortise positions are unaffected. > 0 overrides saddle / edge profile.",

  // Edge profile hints (shared via _helpers.ts)
  legEdge:
    "Default light ease (anti-splinter); subtle chamfer for a refined look; pronounced octagonal cross-section (Ming/Qing style). Stretchers set separately.",
  stretcherEdge:
    "Default light ease (anti-splinter); subtle chamfer to pronounced octagonal cross-section.",
  apronEdge:
    "Default light ease (anti-splinter); subtle chamfer for a refined look. Tapered / splayed legs turn the apron into a trapezoid and the chamfer is ignored.",
  seatEdge:
    "0 = square; gentle ease (won't press the thigh) to a pronounced chamfer / egg-shaped rounded edge. Pick the style (45° / round) below.",
  seatEdgeStyle:
    "Pairs with “Edge size”. At 0 neither setting affects the geometry.",
  seatEdgeBottom:
    "Chamfer on the seat/top *underside* edge. Only effective once the legs are inset — the value is auto-clamped to the leg inset so it never cuts into the apron. Style is shared with the top edge.",
  apronEdgeStyle:
    "Pairs with “Apron edge size”. At 0 neither setting affects the geometry.",
  legEdgeStyle: "Style for the leg edge chamfer (V-bit 45° vs. round-over bit).",
  seatProfile:
    "Whether to scoop the seat. A scooped seat is more comfortable but needs a hand plane or carving router.",
  topPanelPieces:
    "Affects the cut-list / material display. Solid tops wider than ~12 in (300 mm) should be glued up from narrower pieces to resist cupping.",
  backRake:
    "How far the back tilts rearward. 0° = fully vertical; 5° is comfortable, 15° is reclined.",

  // === Stool / chair family (apron, stretcher, legs, seat) ===
  apronThickness: "Horizontal thickness of the apron (perpendicular to the seat edge).",
  apronOffset: "How far the apron's top edge is pulled down from the seat.",
  apronWidth: "Apron height. ~2–2-3/4 in (50–70 mm) suits long benches; taller paired with a thin top reads top-heavy.",
  withApron: "Aprons sit beneath the seat and tie the legs together — adds rigidity.",
  withLowerStretchers: "H-frame configuration — sturdier but uses more material.",
  withCenterStretcher: "Recommended for benches over 1.2 m to prevent sagging.",
  withUnderShelf: "Adds a panel between the lower stretchers for storing shoes / books (auto-enables lower stretchers as support).",
  lowerStretcherFromGround: "Distance from the floor up to the bottom face of the lower stretcher.",

  // === Leg sizing / shapes ===
  legSize: "Default for square legs. If width/depth overrides are filled, those win.",
  legWidthOverride: "0 = use “Leg size”. Non-zero = dimension along the seat's long edge X (lets you make flat legs).",
  legDepthOverride: "0 = use “Leg size”. Non-zero = dimension along the seat's short edge Z.",

  // === Seat (additional) ===
  seatCornerR: "Corner radius of the seat in top view. 0 = sharp corner; ~1-1/4–2 in (30–50 mm) is a common soft corner.",

  // === Footrest (bar stool) ===
  footrestHeight: "Footrest floor height. Bar-stool standard: ~16–18 in (400–450 mm) below the seat. Counter stools sit lower, ~12 in (300 mm) below the seat.",
  footrestWidth: "Vertical height (thickness) of the footrest rail.",
  footrestThickness: "Horizontal thickness (depth) of the footrest rail.",
  footrestStaggerMm: "How much the left/right footrest pair rides above the front/back pair (live 3D update, tenons follow). 0 = even-height (auto half-lap to avoid clash).",

  // === Backrest panel / posts (round-stool, dining chair variants) ===
  backHeight: "Distance from the top of the seat to the top of the backrest.",
  backPanelHeight: "Vertical height of the back panel (rounded rectangle).",
  backPanelCornerR: "Corner radius of the back panel.",
  backPanelBottomArch: "Bottom-edge center offset. Positive = arches up (D-shape / crescent); negative = drops down (skirt). 0 = flat bottom.",
  backPanelTopArch: "Top-edge center offset. Positive = arches up (arched top); negative = dips down (concave top). 0 = flat top.",
  backPanelFaceBend: "How much the panel's large face (front/back) is dished. 0 = flat; larger = more curve (~3/8–1-1/4 in / 10–30 mm recommended for lumbar support).",
  backPanelInset: "Distance from the seat's rear edge forward to the back of the support cylinder. 0 = cylinder rear flush with seat rear.",
  backPanelEmbed: "How deep the back panel embeds into the support cylinders; a flat is removed from each cylinder to match.",
  backPostDiameter: "Diameter of the two round vertical posts supporting the back panel.",
  backPostFromEdge: "Distance from the post's outer face to the left/right end of the back panel. 0 = post outer face flush with panel end.",
  backRailInsetX: "Distance from the seat's left/right end inward to the back post's outer face. 0 = post outer face flush with seat end.",
  backRailInsetZ: "Distance from the seat's rear edge forward to the back post's rear face. 0 = post rear flush with seat rear.",
  backRailPostWidth: "Defaults to ~1 in (25 mm) — narrower than the leg, visually more separated (common on rail/slat backs). 0 = match leg width.",
  backRailPostThickness: "Defaults to ~1 in (25 mm) — narrower than the leg. 0 = match leg thickness.",
  backReclineDeg: "How far the back tilts rearward. The front view still reads vertical; only the side view shows the lean (cylinders and panel tilt together).",
  topRailHeight: "0 = auto (1/3 of back height, capped at ~2 in / 50 mm). A filled value takes priority.",

  // === Misc shared ===
  midHeight: "Only used when total height is locked.",

  // === Toe kick / crown molding (case goods) ===
  withToeKick: "Inset the bottom-front so toes don't hit the case face. Requires leg height = 0 and a leg style other than plinth/side-extended.",
  withCrownMolding: "Adds an outward-projecting molding ring at the top — a classic case-goods detail.",
  backPanelPlywood: "Checked: back panel counts as thin plywood (~3/16–1/4 in / 4–6 mm, saves on lumber). Unchecked: back uses the main material (best visual unity).",

  // === Bench / bar-stool / dining-chair back family ===
  seatHeight: "Floor to top of seat.",
  seatFrontWaterfall: "Heavy front-edge round-over (R20–R30) to relieve thigh pressure.",
  ladderRungs: "Rails sit on the upper half of the back; lowest doesn't touch seat.",
  rearPostMode: "Split = current; continuous-* = rear leg extends as back post.",
};

/**
 * spec.label 繁中字典 — 用 spec.key 當主鍵，跨 26 個 template 共享。
 *
 * 注意：各 template 內 spec.label 仍是 source-of-truth（且可能有 template-
 * specific 措辭，例如 bar-stool 用「椅腳樣式」、square-stool 用「腳樣式」）。
 * 這份 ZH map 提供「跨 template 一致」的中性 label，供需要統一顯示的場景使用。
 * 透過 `specLabel(spec, locale)` 解析時，locale='zh' 一律 fallback 回 spec.label
 * 以保留 template-specific 措辭；明確要中性 ZH label 時用 `SPEC_LABEL_ZH[key]`。
 */
export const SPEC_LABEL_ZH: Record<string, string> = {
  // === Legs ===
  legShape: "腳樣式",
  legSize: "腳粗",
  legWidth: "腳寬 X",
  legDepth: "腳深 Z",
  legHeight: "腳高",
  legInset: "腳內縮",
  legEdge: "腳邊緣處理",
  legWidthOverride: "腳寬覆寫",
  legDepthOverride: "腳深覆寫",
  legPenetratingTenon: "腳上榫頭通透（明榫裝飾）",
  splayAngle: "外斜角度 (°)",
  withLegs: "🦿 有腳",
  withFootboard: "加腳踏板",

  // === Top / Seat ===
  topType: "桌面類型",
  topThickness: "桌面厚",
  seatThickness: "座板厚",
  seatEdge: "座板邊緣處理",
  seatEdgeBottom: "座板下緣",
  seatBendMm: "椅面彎曲",
  seatCornerR: "座板圓角半徑",
  seatPenetratingTenon: "椅面通透（腳頂穿透）",

  // === Apron ===
  apronWidth: "牙條高度",
  apronThickness: "牙條厚度",
  apronDropFromTop: "牙條距座板",
  apronOffset: "牙條偏移",
  apronStaggerMm: "牙條錯開",
  apronEdge: "牙條邊緣處理",
  apronEdgeStyle: "牙條邊緣樣式",
  withApron: "有牙條",
  spandrelStyle: "牙花樣式",
  friezePanel: "壁緣板",

  // === Stretchers ===
  withLowerStretcher: "加下橫撐",
  withLowerStretchers: "加下橫撐",
  withCenterStretcher: "加中央橫撐",
  lowerStretcherStyle: "下橫撐樣式",
  lowerStretcherWidth: "下橫撐高",
  lowerStretcherThickness: "下橫撐厚",
  lowerStretcherHeight: "下橫撐離地高",
  lowerStretcherStaggerMm: "下橫撐錯開",
  lowerStretcherArrangement: "下橫撐排列",
  stretcherStyle: "橫撐樣式",
  stretcherEdge: "橫撐邊緣處理",
  standingBraceStyle: "立撐樣式",

  // === Back / chair-specific ===
  backStyle: "椅背樣式",
  backHeight: "椅背高度",
  backInsetFromEndMm: "椅背距座板端",
  backInsetFromRearMm: "椅背距座板後",
  endSplat: "端板",
  withArmrest: "加扶手",
  armrestHeight: "扶手高度",
  armrestPlankWidth: "扶手板寬",
  armrestPlankThickness: "扶手板厚",
  armrestPostWidth: "扶手前柱 X",
  armrestPostThickness: "扶手前柱 Z",
  rearPostMode: "後柱模式",
  headStyle: "床頭板樣式",

  // === Carcase / panels ===
  panelThickness: "板厚",
  bottomThickness: "底板厚",
  bottomType: "底板類型",
  bottomAttach: "底板固定方式",
  pedestalTopAttach: "桌墩頂面固定方式",
  wallThickness: "壁厚",
  cabinetCorner: "櫃體轉角",
  cornerJoinery: "轉角接合",
  bodyShape: "本體形狀",
  boxShape: "盒體形狀",
  panelStyle: "板樣式",

  // === Layout / zones / columns ===
  layoutMode: "排列模式",
  compoundMode: "複合模式",
  layerCount: "層數",
  layer1Type: "第 1 層類型",
  layer2Type: "第 2 層類型",
  layer3Type: "第 3 層類型",
  layer4Type: "第 4 層類型",
  layer5Type: "第 5 層類型",
  layer6Type: "第 6 層類型",
  layer7Type: "第 7 層類型",
  layer8Type: "第 8 層類型",
  upperType: "上層類型",
  midType: "中層類型",
  bottomType_zone: "下層類型",
  withUpperZone: "加上層",
  leftType: "左欄類型",
  rightType: "右欄類型",
  centerType: "中欄類型",
  leftCount: "左欄列數",
  rightCount: "右欄列數",
  centerCount: "中欄列數",
  left: "左欄",
  right: "右欄",
  front: "前",
  back: "後",
  verticalDividerCount: "垂直分隔板數",
  dividerThickness: "分隔板厚",
  dividerHeight: "分隔板高",
  polygonDividerStyle: "多邊形分隔樣式",
  gridLayout: "格網排列",

  // === Drawers ===
  withDrawer: "加抽屜",
  withPullOutDrawer: "加抽拉屜",
  drawerCount: "抽屜數",
  drawerRows: "抽屜列數",
  drawerStyle: "抽屜樣式",
  drawerSide: "抽屜方向",
  drawerFaceStyle: "抽屜面板樣式",
  drawerBackMode: "抽屜背板模式",
  drawerHeightStyle: "抽屜高度樣式",
  ascendingDrawerCount: "抽屜總數",
  apronDrawerPosition: "牙條抽屜位置",
  apronDrawerWidth: "牙條抽屜寬",
  apronDrawerFrontInset: "抽屜面板內縮",

  // === Doors / handles / hardware ===
  doorType: "門片類型",
  doorStyle: "門片樣式",
  withHandle: "加把手",
  handleShape: "把手形狀",
  pullStyle: "把手樣式",
  withLid: "加蓋",
  lidType: "蓋體類型",

  // === Misc structure ===
  hasLowerShelf: "加下層板",
  withSlatRack: "加條板架",
  withGalleryRail: "加圍欄",
  withLedderRail: "加梯式靠背",
  withBookStop: "加書擋",
  withLazySusan: "加旋轉盤",
  withToeKick: "加踢腳",
  withCrownMolding: "加上緣線板",
  withGrooveBack: "加凹槽背板",
  withRebate: "加企口",
  dropLeaf: "活動桌翼",
  liveEdge: "自然邊",
  lockTotalHeight: "🔒 鎖總高",
  sizingMode: "尺寸模式",
  useCase: "使用情境",
  balustradeStyle: "欄杆樣式",
  angledRack: "傾斜鞋架",
  angledRackTilt: "傾斜角度 (°)",

  // === Tier-2 long-tail ===
  backPanelBottomArch: "背板下緣弧高",
  backPanelCornerR: "曲面背板圓角",
  backPanelEmbed: "靠背圓柱嵌入深度",
  backPanelFaceBend: "曲面背板正面彎曲",
  backPanelHeight: "背板高度",
  backPanelInset: "背板內縮",
  backPanelMaterial: "背板材質",
  leftWidthMm: "左欄寬",
  rightWidthMm: "右欄寬",
  singleLayerLeftWidthMm: "左欄寬",
  singleLayerRightWidthMm: "右欄寬",
  legEdgeStyle: "腳邊緣樣式",
  pedestalTopGap: "桌墩頂面留縫",
  pedestalStretcherHeight: "桌墩橫撐離地高",
  headHeight: "床頭板高度",
  wallHeight: "天花高度",
  ceilingHeight: "天花高度",
  withFrenchCleat: "加 French cleat",

  // Round-table / lazy-susan / center stretcher
  withLazySusanBearing: "旋轉盤軸承",
  withTrim: "加飾條線板",
  withMolding: "加線板",

  // Box / dovetail-box detail
  segmentCount: "分段數",
  angleDeg: "角度 (°)",
  insideDimsMode: "內尺寸模式",

  // Coat rack
  hookCount: "掛鉤數",
  hookHeight: "掛鉤高度",

  // Bed
  mattressLength: "床墊長",
  mattressWidth: "床墊寬",
  slatCount: "床板條數",
};

export function specLabel(spec: OptionSpec, locale: string): string {
  if (locale === "en") {
    const en = SPEC_LABEL_EN[spec.key];
    if (en) return en;
  }
  return spec.label;
}

/** spec.help — EN tooltip lookup; falls back to spec.help (zh). */
export function specHelp(spec: OptionSpec, locale: string): string | undefined {
  if (locale === "en") {
    const en = SPEC_HELP_EN[spec.key];
    if (en) return en;
  }
  return spec.help;
}

/**
 * spec.choices 內 select 選項的 EN label 對應表，key = `${spec.key}:${value}`。
 * 找不到對應就 fallback 回原本的 zh label。
 *
 * 這個表跟 SPEC_LABEL_EN 同樣是漸進式覆蓋；長尾選項先放著，常用 / 高曝光的
 * 先補。當下覆蓋的是 legShape / cornerJoinery / layoutMode / backStyle /
 * pullStyle / doorStyle / drawerStyle / lowerStretcherStyle / bodyShape /
 * stretcherStyle / withLowerStretcher 等高頻 dropdown。
 */
export const CHOICE_LABEL_EN: Record<string, string> = {
  // === legShape ===
  "legShape:box": "Square (straight)",
  "legShape:tapered": "Tapered",
  "legShape:splayed": "Splayed (square)",
  "legShape:splayed-tapered": "Splayed + tapered",
  "legShape:splayed-width": "Splayed (front-back)",
  "legShape:splayed-length": "Splayed (side)",
  "legShape:round": "Round (straight)",
  "legShape:round-tapered": "Round + tapered",
  "legShape:round-taper-up": "Round, taper up",
  "legShape:round-taper-down": "Round, taper down",
  "legShape:splayed-round-taper-up": "Splayed round, taper up",
  "legShape:splayed-round-taper-down": "Splayed round, taper down",
  "legShape:chamfered": "Chamfered",
  "legShape:waisted": "Waisted",
  "legShape:cabriole": "Cabriole",
  "legShape:horse-hoof": "Horse-hoof (Ming)",
  "legShape:reverse-horse-hoof": "Reverse horse-hoof (Qing)",

  // === endSplat (bench backrest style) ===
  "endSplat:none": "None (plain bench)",
  "endSplat:low": "Low solid backrest (lumbar support)",
  "endSplat:high": "High solid backrest (formal seating)",
  "endSplat:slatted": "High slatted back (vertical bars + top rail)",
  "endSplat:ladder": "High ladder back (1–3 horizontal rails + 2 posts)",
  "endSplat:windsor": "Windsor style (turned posts + spindles + bow top rail)",

  // === bodyShape / boxShape ===
  "bodyShape:square": "Square",
  "bodyShape:rect": "Rectangular",
  "bodyShape:round": "Round",
  "bodyShape:hex": "Hexagonal",
  "bodyShape:oct": "Octagonal",
  "boxShape:square": "Square",
  "boxShape:rect": "Rectangular",
  "boxShape:round": "Round",
  "boxShape:hex": "Hexagonal",
  "boxShape:oct": "Octagonal",

  // === backStyle ===
  "backStyle:slat": "Slat back",
  "backStyle:ladder": "Ladder back",
  "backStyle:windsor": "Windsor (spindles)",
  "backStyle:panel": "Solid panel",
  "backStyle:splat": "Single splat",
  "backStyle:fan": "Fan back",
  "backStyle:cross": "Cross back",
  "backStyle:none": "None",

  // === doorType / doorStyle ===
  "doorType:flush": "Flush",
  "doorType:inset": "Inset",
  "doorType:overlay": "Overlay",
  "doorType:glass": "Glass panel",
  "doorType:panel": "Frame and panel",
  "doorType:none": "No doors",
  "doorStyle:flat": "Flat",
  "doorStyle:shaker": "Shaker",
  "doorStyle:panel": "Frame and panel",
  "doorStyle:glass": "Glass",
  "doorStyle:inset-panel": "Inset panel",

  // === drawerStyle ===
  "drawerStyle:flush": "Flush front",
  "drawerStyle:inset": "Inset",
  "drawerStyle:overlay": "Overlay",
  "drawerStyle:shaker": "Shaker",

  // === handle / pullStyle ===
  "pullStyle:none": "None",
  "pullStyle:bar": "▬ Bar pull",
  "pullStyle:knob": "● Knob",
  "pullStyle:wood-knob": "🍄 Wood knob (turned)",
  "pullStyle:cup": "Cup pull",
  "pullStyle:drop-bail": "Drop bail (traditional)",
  "pullStyle:recessed": "Recessed finger pull",
  "handleShape:bar": "▬ Bar pull",
  "handleShape:knob": "● Knob",
  "handleShape:cup": "Cup pull",
  "handleShape:recessed": "Recessed finger pull",
  "handleShape:none": "None",

  // === layoutMode ===
  "layoutMode:vertical": "Vertical",
  "layoutMode:horizontal": "Horizontal",
  "layoutMode:single-layer": "Single tier",
  "layoutMode:h-2col": "Horizontal (2 columns)",
  "layoutMode:h-3col": "Horizontal (3 columns)",
  "layoutMode:v-1col": "Vertical (1 column)",
  "layoutMode:v-2col": "Vertical (2 columns)",

  // === cornerJoinery ===
  "cornerJoinery:through-tenon": "Through tenon",
  "cornerJoinery:blind-tenon": "Blind tenon",
  "cornerJoinery:dovetail": "Dovetail",
  "cornerJoinery:finger-joint": "Finger joint",
  "cornerJoinery:miter": "Miter",
  "cornerJoinery:mitered-spline": "Mitered with spline",
  "cornerJoinery:butt": "Butt joint",
  "cornerJoinery:stub-joint": "Housing joint",
  "cornerJoinery:half-lap": "Half lap",
  "cornerJoinery:rebated": "Rebated",

  // === stretcher style ===
  "lowerStretcherStyle:h-frame": "H-frame (4 stretchers, sturdiest)",
  "lowerStretcherStyle:x-cross": "X-cross (2 diagonal braces)",
  "lowerStretcherStyle:box": "Box (perimeter ring)",
  "lowerStretcherStyle:single": "Single center stretcher",
  "lowerStretcherStyle:none": "None",
  "stretcherStyle:h-frame": "H-frame",
  "stretcherStyle:x-cross": "X-cross",
  "stretcherStyle:box": "Box",
  "stretcherStyle:single": "Single",
  "stretcherStyle:none": "None",
  "standingBraceStyle:h-frame": "H-frame",
  "standingBraceStyle:x-cross": "X-cross",
  "standingBraceStyle:cross": "Cross",
  "standingBraceStyle:none": "None",

  // === withLowerStretcher / generic on-off ===
  // (booleans don't have choices; skipped)

  // === layer / zone / row types (open-bookshelf, chest, etc.) ===
  "upperType:open-shelf": "Open shelf",
  "upperType:drawer-row": "Drawer row",
  "upperType:door-row": "Door row",
  "upperType:glass-door": "Glass door",
  "upperType:none": "None",
  "midType:open-shelf": "Open shelf",
  "midType:drawer-row": "Drawer row",
  "midType:door-row": "Door row",
  "midType:none": "None",
  "bottomType:open-shelf": "Open shelf",
  "bottomType:drawer-row": "Drawer row",
  "bottomType:door-row": "Door row",
  "bottomType:plinth": "Plinth base",
  "bottomType:legs": "Legs",
  "bottomType:none": "None",

  // === edge profile ===
  "seatEdge:square": "Square edge",
  "seatEdge:rounded": "Rounded over",
  "seatEdge:chamfered": "Chamfered",
  "seatEdge:bullnose": "Bullnose",
  "seatEdge:ogee": "Ogee",
  "seatEdge:waterfall": "Waterfall",
  "apronEdge:square": "Square",
  "apronEdge:rounded": "Rounded over",
  "apronEdge:chamfered": "Chamfered",
  "stretcherEdge:square": "Square",
  "stretcherEdge:rounded": "Rounded over",
  "stretcherEdge:chamfered": "Chamfered",
  "legEdge:square": "Square",
  "legEdge:rounded": "Rounded over",
  "legEdge:chamfered": "Chamfered",

  // === apron-drawer position ===
  "apronDrawerPosition:front": "Front apron",
  "apronDrawerPosition:both-sides": "Both side aprons",
  "apronDrawerPosition:left": "Left apron",
  "apronDrawerPosition:right": "Right apron",

  // === drop leaf / lid ===
  "dropLeaf:none": "None",
  "dropLeaf:one-side": "One side",
  "dropLeaf:both-sides": "Both sides",
  "dropLeaf:front": "Front",
  "dropLeaf:back": "Back",
  "lidType:flat": "Flat",
  "lidType:hinged": "Hinged",
  "lidType:slide": "Sliding",

  // === useCase / sizingMode (common select) ===
  "useCase:custom": "Custom",
  "useCase:standard": "Standard",
  "sizingMode:byCount": "By count (overall calculated)",
  "sizingMode:byOverall": "By overall (count calculated)",
  "sizingMode:auto": "Auto",
  "sizingMode:custom": "Custom",

  // === seatProfile (seat scoop) ===
  "seatProfile:flat": "Flat (simplest)",
  "seatProfile:saddle": "Saddle scoop (ergonomic, needs ~5° arc)",
  "seatProfile:scooped": "Twin scoop (~6 mm each side)",
  "seatProfile:waterfall": "Waterfall front (won't dig into thighs)",
  "seatProfile:dished": "Dished centre (single-axis, for long sitting)",

  // === edge style (45° vs rounded) — used by seatEdgeStyle / apronEdgeStyle / stretcherEdgeStyle / legEdgeStyle ===
  "seatEdgeStyle:chamfered": "45° chamfer (V-bit)",
  "seatEdgeStyle:rounded": "Round-over (round bit)",
  "apronEdgeStyle:chamfered": "45° chamfer (V-bit)",
  "apronEdgeStyle:rounded": "Round-over (round bit)",
  "stretcherEdgeStyle:chamfered": "45° chamfer (V-bit)",
  "stretcherEdgeStyle:rounded": "Round-over (round bit)",
  "legEdgeStyle:chamfered": "45° chamfer (V-bit)",
  "legEdgeStyle:rounded": "Round-over (round bit)",

  // === topPanelPieces ===
  "topPanelPieces:1": "Single board (< 300 mm wide)",
  "topPanelPieces:2": "2-board glue-up",
  "topPanelPieces:3": "3-board glue-up (most common, ~200–300 mm each)",
  "topPanelPieces:4": "4-board glue-up (large tops)",

  // === rectLegShape choices (RECT_LEG_SHAPE_CHOICES) ===
  "legShape:strong-taper": "Strong taper (heavily narrowed at bottom)",
  "legShape:inverted": "Inverted taper (thicker at bottom)",

  // === rearPostMode / headStyle ===
  "rearPostMode:integral": "Integral with rear leg",
  "rearPostMode:separate": "Separate post",
  "rearPostMode:none": "None",
  "rearPostMode:split": "Split (separate post)",
  "rearPostMode:continuous-straight": "Continuous straight (A)",
  "rearPostMode:continuous-bent": "Continuous bent (B, lean back)",

  // === backStyle (extra variants from bench / bar-stool / dining-chair) ===
  "backStyle:rail": "Short rail (single bar)",
  "backStyle:slats": "Vertical slats",
  "backStyle:curved-splat": "Curved splat",

  // ── Phase 4 batch: 277 long-tail CHOICE values across 27 templates ──
  "__tray_polygon_disabled__:hex": "Hex (6-piece)",
  "__tray_polygon_disabled__:oct": "Octagonal (8-piece)",
  "__tray_polygon_disabled__:rect": "Rectangular (4 walls, simplest)",
  "apronDrawerPosition:center": "Center",
  "backMode:none": "No back (open shelving)",
  "backMode:rebated": "Rebated (9 mm into side groove) — joinery / country style",
  "backMode:surface": "Nailed back (3 mm ply covers entire back) — typical install",
  "backPanelMaterial:inherit": "↳ Same as primary material",
  "backPanelMaterial:mdf": "MDF (smooth, paint-friendly)",
  "backPanelMaterial:plywood": "Plywood (most common, 4 or 6 mm)",
  "backPanelMaterial:solid": "Solid wood (most expensive, best continuity)",
  "backPanelStyle:framed": "Frame-and-panel (rails + panel)",
  "backPanelStyle:singleBoard": "Single solid panel",
  "balustradeStyle:none": "No gallery rail (standard cabinet)",
  "balustradeStyle:scroll": "Scrollwork (cloud-curve fretwork)",
  "balustradeStyle:vertical": "Vertical spindles (5 thin balusters)",
  "bedPreset:babu-alcove": "Babu alcove bed (1400 mm headboard, premium)",
  "bedPreset:custom": "Custom (no preset)",
  "bedPreset:huanghuali-4post": "Huanghuali 4-post (1300 mm head, with footboard)",
  "bedPreset:industrial": "Industrial (heavy straight legs, low head)",
  "bedPreset:japanese-platform": "Japanese platform (tatami, low head)",
  "bedPreset:kids": "Kids bed (thin legs, low, footboard rail)",
  "bedPreset:ming-canopy": "Ming canopy (tall head, with footboard)",
  "bedPreset:nordic": "Nordic minimal (tapered legs, low head, no footboard)",
  "bedPreset:storage-lift": "High-leg storage lift (tall sides, hidden storage)",
  "bottleType:bordeaux": "Bordeaux (⌀75 mm, narrow shoulder)",
  "bottleType:burgundy": "Burgundy (⌀80 mm, broad shoulder)",
  "bottleType:champagne": "Champagne (⌀90 mm, widest)",
  "bottleType:custom": "Custom diameter",
  "bottomAttach:flush-glued": "Flush glued (bottom panel flush with frame)",
  "bottomAttach:inset-panel": "Inset panel (groove all four walls, panel slides in)",
  "bottomAttach:seated": "Seated (panel sits on floor, walls glue above — simplest)",
  "boxUse:cigar": "Cigar humidor (thick wall, dovetails, humidity-resistant)",
  "boxUse:custom": "Custom (no preset)",
  "boxUse:document": "Document box (thick wall, finger joint, large)",
  "boxUse:jewelry": "Jewelry box (thin wall, dovetails, removable tray, dividers)",
  "boxUse:tea": "Tea caddy (mid wall, dovetails, moisture-resistant)",
  "boxUse:watch": "Watch box (thin wall, dovetails, 4 horizontal cells)",
  "cabinetCorner:round": "Round corner (tapered sides, splayed top, wood-pivot doors)",
  "cabinetCorner:square": "Square corner (vertical posts, brass hinges, right angles)",
  "cabinetPreset:bookshelf": "Bookshelf (5 fully-open shelves)",
  "cabinetPreset:cupboard": "Cupboard (door + drawer + door)",
  "cabinetPreset:custom": "Custom (define layers below)",
  "cabinetPreset:display-cabinet": "Display cabinet (4 layers with glass lattice doors)",
  "cabinetPreset:glass-bookshelf": "Glass bookshelf (5 layers, all glass doors)",
  "cabinetPreset:round-cabinet": "Round-corner cabinet (Ming classic — tapered, splayed top, wood pivot)",
  "cabinetPreset:shrine": "Altar side cabinet (drawer + door + shelf)",
  "cabinetPreset:tea-cabinet": "Tea cabinet (drawer + door + shelf)",
  "cabinetPreset:top-cabinet": "Top-box cabinet (Ming/Qing — small upper + large lower)",
  "cabinetPreset:wanli-cabinet": "Wanli cabinet (open top + lower closed, vertical spindle rail, study classic)",
  "centerCount:deep-shallow": "Deep below, shallow above 3:2",
  "centerCount:shallow-mid-deep": "Shallow-mid-deep 2:3:4 (3-row only)",
  "centerDrawerRowRatio:equal": "Equal split (default)",
  "centerDrawerRowRatio:shallow-deep": "Shallow above, deep below 2:3",
  "columnStyle:box": "Box column (straight square stock)",
  "columnStyle:lathe-turned": "Lathe-turned (classical vase silhouette, most iconic)",
  "columnStyle:round": "Round (straight round stock)",
  "compoundMode:single": "Single section (standard square-corner cabinet)",
  "compoundMode:topBox": "Top-box (small upper + larger lower stacked)",
  "doorMullion:art-deco": "Art Deco geometric (diamond / fan)",
  "doorMullion:colonial": "Colonial 6-light (colonial style)",
  "doorMullion:cross": "Cross 4-light (classic)",
  "doorMullion:none": "Single pane (simplest)",
  "doorMullion:vertical-3": "Vertical 3-light",
  "doorPullStyle:bar": "▮ Long bar pull (auto-vertical on doors)",
  "doorPullStyle:drop-bail": "⌒ Drop bail (Hepplewhite)",
  "doorPullStyle:inherit": "↳ Same as drawer pull",
  "doorPullStyle:knob": "● Brass round knob",
  "doorPullStyle:none": "✕ None",
  "doorPullStyle:ring-chinese": "◎ Chinese ring pull (antique brass)",
  "doorPullStyle:wood-knob": "🍄 Wooden turned knob",
  "doorPullType:none": "None",
  "doorPullType:round-brass": "Round brass ring",
  "doorPullType:strip": "Brass strip",
  "doorStyle:glass-lattice": "Glass lattice door (cross fretwork with glass behind)",
  "doorStyle:lattice-cross": "Lattice door: cross grid (orthogonal mullions)",
  "doorStyle:lattice-lantern": "Lattice door: lantern pattern (米-shape mullions)",
  "doorStyle:solid": "Single solid panel",
  "doorType:louvered": "Louvered (ventilated, anti-odor)",
  "doorType:slab": "Plywood-veneer slab door (standard install)",
  "doorType:wood": "Wood-frame panel door",
  "drawerBackMode:none": "No back (open rear)",
  "drawerBackMode:rebated": "Rebated (panel between sides, clean look)",
  "drawerBackMode:surface": "Nailed (thin panel nailed on rear)",
  "drawerBottomMode:rebated": "Rebated (panel into side-bottom grooves, clean look)",
  "drawerBottomMode:surface": "Nailed (thin panel nailed under sides)",
  "drawerBottomThickness:12": "12 mm (typical solid)",
  "drawerBottomThickness:3": "3 mm (thin ply)",
  "drawerBottomThickness:9": "9 mm (standard)",
  "drawerBoxJoinery:dovetail": "Dovetail (traditional solid wood)",
  "drawerBoxJoinery:lap": "Lap joint (butt + screws/dowels, simplest)",
  "drawerCount:shaker": "Shaker leg (top 1/4 square, bottom 3/4 round taper)",
  "drawerCount:splayed-length": "Splayed leg (single-axis along length)",
  "drawerCount:splayed-round-tapered": "Round tapered + splayed",
  "drawerCount:splayed-tapered": "Tapered + splayed (square stock)",
  "drawerCount:splayed-width": "Splayed leg (single-axis along width)",
  "drawerCount:splayed": "Splayed legs (4-corner outward)",
  "drawerFaceStyle:flat": "Flat slab (modern minimal)",
  "drawerFaceStyle:raised-panel": "Raised panel (traditional frame + center panel)",
  "drawerHeightStyle:ascending": "Larger below, smaller above (Ming/Qing 1.4:1.2:1)",
  "drawerHeightStyle:equal": "Equal heights (modern)",
  "drawerInternalGrid:divided-2": "Vertical divider (2 cells)",
  "drawerInternalGrid:divided-4": "Cross divider (4 cells)",
  "drawerInternalGrid:none": "No divider (single cell)",
  "drawerMount:inset": "Inset (face flush with opening)",
  "drawerMount:overlay-3": "3/8 overlay (half-overlay, face overlaps 9 mm)",
  "drawerMount:overlay-6": "6/8 overlay (full overlay, face covers all)",
  "drawerPullStyle:bar": "▬ Long bar pull (modern minimal)",
  "drawerPullStyle:drop-bail": "⌒ Drop bail (Hepplewhite)",
  "drawerPullStyle:knob": "● Brass round knob (traditional)",
  "drawerPullStyle:none": "✕ None (display only)",
  "drawerPullStyle:ring-chinese": "◎ Chinese ring pull (antique brass)",
  "drawerPullStyle:wood-knob": "🍄 Wooden turned knob",
  "drawerPullType:none": "None",
  "drawerPullType:round-brass": "Round brass ring",
  "drawerPullType:strip": "Brass strip",
  "drawerRowRatio:equal": "Equal split (default)",
  "drawerRowRatio:shallow-deep": "Shallow above, deep below 2:3 (remotes vs cables)",
  "drawerRows:deep-shallow": "Deep below, shallow above 3:2",
  "drawerRows:shallow-mid-deep": "Shallow-mid-deep 2:3:4 (3-row only)",
  "drawerSide:center": "Center (narrow type)",
  "drawerSide:left": "Left",
  "drawerSide:right": "Right",
  "drawerSlideType:none": "No slides (wood-on-wood, 1 mm/side clearance)",
  "drawerSlideType:side-mount": "Side-mount ball-bearing slides (12.5 mm/side)",
  "drawerSplit:double": "Two cells (center divider)",
  "drawerSplit:single": "Single cell",
  "drawerSplit:triple": "Three cells",
  "drawerStyle:apron": "Apron-band drawer (thin drawer along front apron)",
  "drawerStyle:none": "No drawer",
  "drawerStyle:pedestal": "Pedestal drawer (hung beneath the desktop)",
  "dropLeaf:two-sides": "Two-side drop leaf (extends both ends)",
  "frameProfile:chamfer-out": "Outer 45° chamfer",
  "frameProfile:flat": "Flat (simplest)",
  "friezePanel:lattice": "Lattice frieze (cross / grid pattern)",
  "friezePanel:none": "No frieze panel",
  "friezePanel:openwork": "Openwork frieze (cloud / scroll fretwork)",
  "gridLayout:diamond": "Diamond grid (bw×bt equal diamonds, cellar classic)",
  "gridLayout:rect": "Rectangular grid (orthogonal, max bottles)",
  "handleShape:circle": "Circle (single round hole, smallest)",
  "handleShape:pill": "Pill (rounded rectangle)",
  "handleShape:rect": "Rectangle (sharp corners, simplest)",
  "headStyle:arched": "Arched (curved top, modern)",
  "headStyle:crested": "Crested (raised center, Victorian)",
  "headStyle:fielded": "Fielded panel (raised center with bevel)",
  "headStyle:panel-frame": "Frame-and-panel (frame + center panel, Huanghuali / babu)",
  "headStyle:panel": "Flat panel (single board, simplest)",
  "headStyle:slatted-horizontal": "Horizontal slats (N rails, Scandinavian)",
  "headStyle:spindled": "Vertical spindles (N posts, Ming / kids)",
  "headStyle:tufted-look": "Tufted look (panel-divided fake-upholstered)",
  "hiddenDrawerLayer:1": "Layer 1 is hidden drawer",
  "hiddenDrawerLayer:2": "Layer 2 is hidden drawer",
  "hiddenDrawerLayer:3": "Layer 3 is hidden drawer",
  "hiddenDrawerLayer:4": "Layer 4 is hidden drawer",
  "hiddenDrawerLayer:5": "Layer 5 is hidden drawer",
  "hiddenDrawerLayer:6": "Layer 6 is hidden drawer",
  "hiddenDrawerLayer:7": "Layer 7 is hidden drawer",
  "hiddenDrawerLayer:8": "Layer 8 is hidden drawer",
  "hiddenDrawerLayer:none": "No hidden drawer",
  "layoutMode:v-1layer": "Single vertical layer (one type)",
  "layoutMode:v-2layer": "Two vertical layers (upper shelves + lower drawers)",
  "leftCount:deep-shallow": "Deep below, shallow above 3:2",
  "leftCount:shallow-mid-deep": "Shallow-mid-deep 2:3:4 (3-row only)",
  "leftDrawerRowRatio:equal": "Equal split (default)",
  "leftDrawerRowRatio:shallow-deep": "Shallow above, deep below 2:3",
  "legShape:auto": "Auto from proportion style (Ming=inward hoof, Qing=outward hoof)",
  "legShape:bracket": "Bracket foot",
  "legShape:fluted-square": "Classical square (fluted on 4 faces)",
  "legShape:heavy-round-taper": "Heavy round taper (strong downward narrowing)",
  "legShape:inward-hoof": "Inward horse-hoof (Ming style)",
  "legShape:outward-hoof": "Outward horse-hoof (Qing style, heavy)",
  "legShape:panel-side": "Panel-side extension (continuous side panel down to floor)",
  "legShape:pedestal": "Pedestal (single thick column + 4-claw foot)",
  "legShape:plinth": "Plinth base (continuous board)",
  "legShape:shaker": "Shaker leg (square top + round taper)",
  "legShape:trestle": "Trestle (end frames + central stretcher)",
  "legShape:windsor": "Windsor (turned + round legs + curved bow top)",
  "lidType:lift-off": "Lift-off (4 walls split horizontally, top half is the lid, hinged)",
  "lidType:rabbeted": "Rabbeted (lid edge laps onto box rim)",
  "lidType:sliding": "Sliding (front/back walls have inside grooves, lid slides in)",
  "lowerStretcherArrangement:box-frame": "Box frame (4 sides, most stable, default)",
  "lowerStretcherArrangement:double-rail": "Double rail (4 sides + lower row of 4)",
  "lowerStretcherArrangement:h-frame": "H-frame (2 sides + 1 center)",
  "lowerStretcherArrangement:pair-x": "Pair-X (front + back only, no sides)",
  "lowerStretcherArrangement:pair-z": "Pair-Z (left + right only, no front/back)",
  "mountType:standing": "Standing (4 legs, traditional)",
  "mountType:wall-rail": "Wall-mounted Shaker peg rail (board + N pegs, entry classic)",
  "panelInlay:calligraphy-frame": "Calligraphy frame (centered space for art / couplets)",
  "panelInlay:latticed-center": "Latticed center (cross grid in middle)",
  "panelInlay:none": "No inlay (plain panel)",
  "panelInlay:stone-medallion": "Stone medallion (round / square marble inset)",
  "panelStyle:flat": "Flat panel",
  "panelStyle:raised": "Raised panel (5 mm raise in center)",
  "pedestalTopAttach:both": "Both pedestals extend to top",
  "pedestalTopAttach:brass-pillars": "4 brass pillars (modern minimal)",
  "pedestalTopAttach:none": "No top attach (H-frame supports only)",
  "pedestalTopAttach:single": "Single pedestal extends (traditional pedestal desk)",
  "polygonDividerStyle:cross": "Cross (2 panels through center)",
  "polygonDividerStyle:none": "No divider",
  "polygonDividerStyle:single": "Single diameter (one panel through center)",
  "postEndStyle:exposedTenon": "Exposed tenon (decorative)",
  "postEndStyle:flush": "Flush top (hidden)",
  "proportionStyle:free": "Custom (use entered dimensions)",
  "proportionStyle:ming": "Ming (tall narrow, H:W ≈ 1.8)",
  "proportionStyle:qing": "Qing (short wide, H:W ≈ 1.2)",
  "pullPosition:center": "Single pull, center",
  "pullPosition:dual": "Dual pulls (left + right, traditional chest)",
  "pullStyle:ring-chinese": "◎ Chinese ring pull (Ming/Qing cabinet door / drawer)",
  "rackStyle:classic": "Classic turned (lathe-turned + 4 feet + 8 hooks)",
  "rackStyle:custom": "Custom (no preset)",
  "rackStyle:hall-tree": "Hall tree (large with mirror + hat rail)",
  "rackStyle:industrial": "Industrial (square post + 3 feet)",
  "rackStyle:kids": "Kids low (thin post + 3 feet)",
  "rackStyle:modern": "Modern minimal (square post + 3 feet + 6 hooks)",
  "reinforcementPosition:back": "Rear (hidden)",
  "reinforcementPosition:both": "Front + back (strongest)",
  "reinforcementPosition:front": "Front (exposed — English bookshelf face frame)",
  "rightCount:deep-shallow": "Deep below, shallow above 3:2",
  "rightCount:shallow-mid-deep": "Shallow-mid-deep 2:3:4 (3-row only)",
  "rightDrawerRowRatio:equal": "Equal split (default)",
  "rightDrawerRowRatio:shallow-deep": "Shallow above, deep below 2:3",
  "shelfOrientation:length": "Along length (slats span front-back stretchers)",
  "shelfOrientation:width": "Along width (slats span side stretchers, 90°)",
  "shelfSlatEdgeStyle:chamfered": "45° chamfer (V-cutter)",
  "shelfSlatEdgeStyle:rounded": "Round (roundover bit)",
  "singleLayerCols:1": "No division (full-width)",
  "singleLayerCols:2": "2 columns (1 vertical divider)",
  "singleLayerCols:3": "3 columns (2 vertical dividers)",
  "skirtStyle:arched": "Arched apron (downward curve)",
  "skirtStyle:auto": "Auto from proportion style (Ming=arched, Qing=cloud-head)",
  "skirtStyle:cloud-head": "Cloud-head (both ends curved up)",
  "skirtStyle:straight": "Straight (plainest)",
  "slidingLidStyle:flat": "Flat (lid sits below wall top by sinkMm, walls have cap)",
  "slidingLidStyle:raised-center": "Raised center (lid flush with wall top in middle, side rails keep groove)",
  "spandrelStyle:auto": "Auto from proportion style (Ming=ruyi, Qing=cloud-head, custom=none)",
  "spandrelStyle:cloud-head": "Cloud-head spandrel (Qing, heavy)",
  "spandrelStyle:none": "No spandrel",
  "spandrelStyle:ruyi": "Ruyi spandrel (Ming, elegant)",
  "standingBraceStyle:cloud": "Cloud-head standing brace (Qing, heavy)",
  "standingBraceStyle:scroll": "Scroll standing brace (Ming, elegant)",
  "stretcherStyle:side-only": "Sides only (left + right, no front/back)",
  "topDecor:balustrade": "Balustrade gallery (small spindle row, Western cabinet)",
  "topDecor:dentil": "Dentil molding (Greek-revival small teeth)",
  "topDecor:flat-band": "Flat band (60 mm board around top)",
  "topDecor:none": "None (minimal)",
  "topDecor:stepped": "Stepped molding (two-layer cap, traditional)",
  "topType:door": "Doors (shoes hidden)",
  "topType:drawer": "Drawers",
  "topType:shelves": "Open shelves (straight / angled shoe racks)",
  "upperType:door": "Doors",
  "upperType:drawer": "Drawers",
  "upperType:shelves": "Open shelves",
  "useCase:catchall": "Entry catch-all tray (5° splay + short pill handles)",
  "useCase:classic": "Simple square box (lap joints, empty inside, entry level)",
  "useCase:dovetail-classic": "Dovetail dinner tray (traditional + grooved panel bottom, no handles)",
  "useCase:hex-tea-canister": "Hex tea canister (hex + grooved panel bottom)",
  "useCase:kitchen-deep": "Deep kitchen tray (12 mm wall + 1 divider + handle)",
  "useCase:makeup-brush": "Makeup brush holder (square + 1 vertical divider)",
  "useCase:oct-crossed": "Octagonal cross caddy (oct + cross center + flush glue)",
  "useCase:shaker-tea-tray": "Shaker tea tray (15° splay + compound miter + pill handles)",
  "useCase:stationery-grid": "Stationery grid tray (finger joint + 9-cell grid, no handles)",
  "useCase:woodworker-caddy": "Woodworker's caddy (square + 9 cells + grooved panel)",
};

export function choiceLabel(
  specKey: string,
  value: string,
  originalLabel: string,
  locale: string,
): string {
  if (locale !== "en") return originalLabel;
  return CHOICE_LABEL_EN[`${specKey}:${value}`] ?? originalLabel;
}
